spinnaker/front50

front50-web/front50-web.gradle

only point at /opt in the startScripts

---

front50-web/front50-web.gradle

See: https://github.com/spinnaker/spinnaker/pull/571

Consistent naming for packages

---

build.gradle

Uses the new functionality in the spinnaker-gradle-project for pinning the version

Pins version of spinnaker-dependencies manifest file

---

build.gradle
front50-cassandra/src/main/groovy/com/netflix/spinnaker/front50/model/application/CassandraApplicationDAO.groovy
front50-cassandra/src/main/groovy/com/netflix/spinnaker/front50/model/project/CassandraProjectDAO.groovy
front50-pipelines/src/main/groovy/com/netflix/spinnaker/front50/notifications/NotificationRepository.groovy
front50-pipelines/src/main/groovy/com/netflix/spinnaker/front50/pipeline/PipelineRepository.groovy
front50-pipelines/src/main/groovy/com/netflix/spinnaker/front50/pipeline/StrategyRepository.groovy
front50-pipelines/src/test/groovy/com/netflix/spinnaker/front50/notifications/NotificationsRepositorySpec.groovy
front50-pipelines/src/test/groovy/com/netflix/spinnaker/front50/pipeline/PipelineRepositorySpec.groovy
front50-pipelines/src/test/groovy/com/netflix/spinnaker/front50/utils/AbstractCassandraBackedSpec.groovy

keyspaces are now initialized in PostConstruct instead of on context refresh
Depends on spinnaker/kork#27
@ajordens ptal

updates to latest kork-cassandra

---

front50-web/config/front50.yml
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/ApplicationsController.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/CredentialsController.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/v2/ProjectsController.groovy

Use the correct annotation packages so the annotations are picked up by Swagger2.
@ajordens or @tomaslin please review.

Add config to enable swagger.

---

front50-s3/src/main/java/com/netflix/spinnaker/front50/model/S3Support.java

- The refresh will (currently) fail and be re-picked up next iteration (no harm no foul really beyond an exception)
- This change has the refresh succeeding by removing/skipping the deleted item

It's possible that an item could be removed mid-refresh cycle

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PipelineController.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/StrategyController.groovy

avoid hitting NPE when running in s3 mode and checking for duplicates

---

front50-cassandra/src/main/groovy/com/netflix/spinnaker/front50/model/application/CassandraApplicationDAO.groovy
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/application/ApplicationDAO.groovy
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/pipeline/Pipeline.groovy
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/pipeline/PipelineDAO.groovy
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/pipeline/PipelineStrategyDAO.groovy
front50-pipelines/src/main/groovy/com/netflix/spinnaker/front50/pipeline/PipelineRepository.groovy
front50-pipelines/src/main/groovy/com/netflix/spinnaker/front50/pipeline/StrategyRepository.groovy
front50-s3/src/main/java/com/netflix/spinnaker/front50/model/S3ApplicationDAO.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/model/S3PipelineDAO.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/model/S3PipelineStrategyDAO.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/model/S3Support.java
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/ApplicationsController.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PipelineController.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/StrategyController.groovy

- Applications/Pipelines/Pipeline Strategies (to start)
- Only supported by S3 (Cassandra will return [])

History support

---

build.gradle
front50-cassandra/src/main/groovy/com/netflix/spinnaker/front50/config/CassandraConfig.groovy
front50-cassandra/src/main/groovy/com/netflix/spinnaker/front50/model/application/CassandraApplicationDAO.groovy
front50-cassandra/src/main/groovy/com/netflix/spinnaker/front50/model/project/CassandraProjectDAO.groovy
front50-cassandra/src/test/groovy/com/netflix/spinnaker/front50/model/application/CassandraApplicationDAOSpec.groovy
front50-redis/front50-redis.gradle
front50-redis/src/main/groovy/com/netflix/spinnaker/front50/redis/RedisApplicationDAO.groovy
front50-redis/src/main/groovy/com/netflix/spinnaker/front50/redis/RedisConfig.groovy
front50-redis/src/main/groovy/com/netflix/spinnaker/front50/redis/RedisNotificationDAO.groovy
front50-redis/src/main/groovy/com/netflix/spinnaker/front50/redis/RedisPipelineDAO.groovy
front50-redis/src/main/groovy/com/netflix/spinnaker/front50/redis/RedisPipelineStrategyDAO.groovy
front50-redis/src/main/groovy/com/netflix/spinnaker/front50/redis/RedisProjectDAO.groovy
front50-redis/src/test/groovy/com/netflix/spinnaker/front50/redis/RedisApplicationDAOSpec.groovy
front50-redis/src/test/groovy/com/netflix/spinnaker/front50/redis/RedisNotificationDAOSpec.groovy
front50-redis/src/test/groovy/com/netflix/spinnaker/front50/redis/RedisPipelineDAOSpec.groovy
front50-redis/src/test/groovy/com/netflix/spinnaker/front50/redis/RedisPipelineStrategyDAOSpec.groovy
front50-redis/src/test/groovy/com/netflix/spinnaker/front50/redis/RedisProjectDAOSpec.groovy
front50-redis/src/test/groovy/com/netflix/spinnaker/front50/redis/RedisTestHelper.groovy
front50-redis/src/test/resources/application.yml
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3Config.java
front50-web/config/front50.yml
front50-web/front50-web.gradle

* Make entire S3 module optional
* Switch Cassandra to be disabled by default

Add option to run on top of Redis

---

front50-s3/src/main/java/com/netflix/spinnaker/front50/model/S3ApplicationDAO.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/model/S3Support.java

always use cache for searches

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/serviceaccount/ServiceAccount.groovy
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/serviceaccount/ServiceAccountDAO.groovy
front50-gcs/src/main/java/com/netflix/spinnaker/front50/config/GcsConfig.java
front50-gcs/src/main/java/com/netflix/spinnaker/front50/model/ServiceAccountBucketDAO.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3Config.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/model/S3ServiceAccountDAO.java
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/ServiceAccountsController.groovy

Moving static configuration of service accounts from Fiat to Front50.
@cfieber @duftler @jtk54 PTAL
@ajordens FYI

Adds Service Account model object, DAOs, and controller.

---

front50-gcs/src/main/java/com/netflix/spinnaker/front50/model/GcsStorageService.java

Prevent NPE from GCS bucket versioning

---

front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3Config.java

To use edit config/spinnaker-local.yml:
- storage_bucket: YOUR_S3_BUCKET
- bucket_root: front50
- region: eu-central-1
- proxyHost: webproxy.foo.bar
- proxyPort: 8080
- proxyProtocol: HTTP
Currently only works with proxies without credentials

run front50 with S3 backend behind a corporate proxy

---

front50-migrations/front50-migrations.gradle
front50-migrations/src/main/java/com/netflix/spinnaker/front50/config/MigrationConfig.java
front50-migrations/src/main/java/com/netflix/spinnaker/front50/migrations/LinearToParallelMigration.java
front50-migrations/src/main/java/com/netflix/spinnaker/front50/migrations/Migration.java
front50-migrations/src/main/java/com/netflix/spinnaker/front50/migrations/MigrationRunner.java
front50-migrations/src/test/groovy/com/netflix/spinnaker/front50/migrations/LinearToParallelMigrationSpec.groovy
front50-web/front50-web.gradle

- An initial migrator that will convert linear pipelines to parallel (valid until 2016-09-01)

Generic migration support

---

front50-gcs/src/main/java/com/netflix/spinnaker/front50/model/GcsStorageService.java

Fix GCS history retrieval

---

front50-gcs/src/main/java/com/netflix/spinnaker/front50/model/GcsStorageService.java
front50-gcs/src/test/groovy/com/netflix/spinnaker/front50/model/GoogleStorageServiceSpec.groovy

Fixed GCS delete and timestamp update errors

---

front50-core/front50-core.gradle
front50-core/src/main/groovy/com/netflix/spinnaker/front50/support/ClosureHelper.groovy
front50-core/src/test/groovy/com/netflix/spinnaker/front50/model/application/ApplicationModelSpec.groovy
front50-s3/src/main/java/com/netflix/spinnaker/front50/model/S3Support.java
front50-web/src/main/groovy/com/netflix/spinnaker/front50/config/Front50WebConfig.groovy

- Avoids a scenario where S3 is unavailable for brief periods of time

Tactical application of hystrix to S3Support

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PipelineController.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/SnapshotsController.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/StrategyController.groovy

This PR is based off of #123 , so please review the **second** commit only.
Adds Pipeline, Strategy, and Snapshot annotation authorization checks.  There are two endpoints I'm not sure how to secure, both of them are DELETE by [pipeline|strategy] ID. It's not immediately clear if this endpoint is even used, instead using the application/pipelineID deletion endpoint. 
@ajordens @cfieber @duftler @jtk54 PTAL.

Bulk of Front50 endpoint authorization checks

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/snapshot/Snapshot.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/SnapshotsController.groovy

Added an endpoint for getting a snapshot by timestamp. Did I add the correct authentication annotation @ttomsu? PTAL @lwander @duftler

provider/core: Created an endpoint for getting a specific snapshot version from buckets

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PermissionsController.groovy

@jtk54 PTAL
tag: https://github.com/spinnaker/fiat/issues/43

Adds delete endpoint for app permissions

---

.editorconfig
front50-web/src/main/groovy/com/netflix/spinnaker/front50/config/Front50WebConfig.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/ApplicationsController.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/exception/ApplicationNotFoundException.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/exception/InvalidApplicationRequestException.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/exception/NoApplicationsFoundException.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/v2/ApplicationsController.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/v2/ApplicationsControllerTck.groovy

Added a V2 API for application with minor tweaks & cleanup.
@ajordens

Add V2 Application API endpoints

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/ApplicationsController.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/v2/ApplicationsController.groovy

tag: https://github.com/spinnaker/fiat/issues/48
@jtk54 PTAL

Remove CREATE application authorization.

---

front50-gcs/src/main/java/com/netflix/spinnaker/front50/model/BucketDAO.java

@duftler 
This is only findById, but that's all that is on the S3 side.
@ajordens 
Are there other access points? Also, if we can do the refactoring we discussed over the summer then this should be easier to maintain (at least this case is in the system-independent part that is intended to be in the front50 core).

Added Hystrix support

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/application/Application.groovy

fix NPE if cluster has no applications

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/application/ApplicationDAO.groovy
front50-core/src/test/groovy/com/netflix/spinnaker/front50/model/application/ApplicationDAOSpec.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/v2/ApplicationsController.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/v2/ApplicationsControllerTck.groovy

Simple algorithm based on:
- strength of match (ie. number of characters matched between search criteria and value)
- position of match (higher scores if match occurs at start of value)

Support rudimentary Application sorting (w/ pageSize)

---

front50-cassandra/src/test/groovy/com/netflix/spinnaker/front50/model/application/CassandraApplicationDAOSpec.groovy
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/application/ApplicationDAO.groovy
front50-redis/src/test/groovy/com/netflix/spinnaker/front50/redis/RedisApplicationDAOSpec.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/v2/ApplicationsControllerTck.groovy

- Removed block where a NotFoundException was being thrown on empty search result set

Fix an unintended 404 on application search of non existent application

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/application/Application.groovy

Adds empty list to requiredGroupMembership

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/v2/ProjectsController.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/v2/ProjectsControllerTck.groovy

- Converted Hal returns to POJOs for consistency

Refactor Project;s API

---

build.gradle
front50-web/front50-web.gradle

Front50: Bumps spinnaker-dependencies version

---

front50-s3/front50-s3.gradle
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PipelineController.groovy

`checkForDuplicatePipeline` should be case insensitive

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/exception/BadRequestException.groovy
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/tag/EntityTags.groovy
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/tag/EntityTagsDAO.groovy
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3Config.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/model/S3EntityTagsDAO.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/model/S3Support.java
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/v2/TagController.groovy

First stab at storing tagged entities in Front50

---

build.gradle
front50-web/front50-web.gradle

Adds stackdriver and update dependencies to 0.63.0

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PermissionsController.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/ServiceAccountsController.groovy

@duftler @jtk54 @ajordens @cfieber PTAL
Fixes https://github.com/spinnaker/fiat/issues/111

Calls Fiat sync when service accounts are created or deleted.

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PipelineController.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/StrategyController.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/PipelineControllerTck.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/StrategyControllerTck.groovy

- The plan is to use this endpoint for general pipeline updates

Adding update pipeline & strategy endpoints

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/v2/ProjectsController.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/v2/ProjectsControllerTck.groovy

- Added an explicit handler to accept a exception message to bubble up

Allow exceptions messages in projects to bubble all the way up

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/config/Front50WebConfig.groovy

Adds service account DAO health indicator

---

front50-gcs/src/main/java/com/netflix/spinnaker/front50/config/GcsConfig.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3Config.java
front50-web/src/main/groovy/com/netflix/spinnaker/front50/config/Front50WebConfig.groovy

@cfieber @duftler @ewiseblatt PTAL
@gardleopard FYI

Adds more threads to S3 pool.

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PermissionsController.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/ServiceAccountsController.groovy

shortcircuit fiat calls if fiat is disabled

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/config/Front50WebConfig.groovy

I mistakenly removed this `@Conditional` in https://github.com/spinnaker/front50/commit/5df60c9728b9598f66fd6817c066dab030f2aca2#diff-5bb302f8a8451b6074552121f57eb504L104 .
@lwander @dennismartensson FYI

Add conditionals on Fiat beans

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/SearchUtils.groovy
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/application/ApplicationDAO.groovy
front50-core/src/test/groovy/com/netflix/spinnaker/front50/model/application/ApplicationDAOSpec.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/v2/ProjectsController.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/v2/ProjectsControllerTck.groovy

- Added support for a fuzzy string match on object attributes
- Added support for pageSize similar to applications
- Search is case insensitive on key and value and allows searching even deep attributes on the object
- Using the same ranking algo for search result relevance as applications (Worth to note that this doesnt apply to deep properties)

Adding support for searching project by a variety of keywords

---

front50-gcs/src/main/java/com/netflix/spinnaker/front50/model/GcsStorageService.java

@ttomsu FYI
@ajordens please review.
The main point is adding a hook to the StorageService interface to initialize a DAO so I can avoid logging errors that were causing concern for some customers while still keeping the errors should the files be deleted during execution.

Added object init to StorageService.

---

halconfig/front50.yml

Base front50 halconfig

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/serviceaccount/ServiceAccount.groovy

Needed for https://github.com/spinnaker/fiat/pull/128
@duftler @jtk54 PTAL
tag: https://github.com/spinnaker/fiat/issues/126

Adds 'memberOf' field to ServiceAccount class

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PermissionsController.groovy

@jtk54 @duftler PTAL
cc @msloes

Trims required group membership entries of whitespace

---

front50-web/front50-web.gradle

@jtk54 PTAL
@cfieber @ajordens FYI

Fiat bump to add LDAP role source.

---

Dockerfile
Dockerfile.slim
build.gradle
cloudbuild.yaml

Slim build & spinnaker gradle project

---

front50-azure/front50-azure.gradle
front50-azure/src/main/java/com/netflix/spinnaker/front50/config/AzureStorageConfig.java
front50-azure/src/main/java/com/netflix/spinnaker/front50/config/AzureStorageProperties.java
front50-azure/src/main/java/com/netflix/spinnaker/front50/model/AzureStorageService.java
front50-web/front50-web.gradle
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PermissionsController.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/ServiceAccountsController.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/SnapshotsController.groovy

Added support for targeting Azure Storage services for persistent storage

Implementing support for Azure Storage

---

halconfig/front50.yml

(halconfig) disable cassandra

---

build.gradle
front50-gcs/src/main/java/com/netflix/spinnaker/front50/model/GcsStorageService.java

(google) Support newer GoogleCommonSafeRetry.doRetry() interface.

(core) Increase spinnaker-dependencies version.

---

front50-azure/src/main/java/com/netflix/spinnaker/front50/config/AzureStorageConfig.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/tag/DefaultEntityTagsDAO.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3Config.java
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/v2/EntityTagsController.groovy

This supports the current clouddriver elasticsearch reindex behavior.

Cache all entity tags

---

front50-gcs/src/main/java/com/netflix/spinnaker/front50/config/GcsConfig.java

feat(gce) Allow entity tags to be stored in GCS

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/v2/ProjectsController.groovy

- adjusted search to use find and not collect on the test
- also ensuring that passed queries are non-null

Fixing a bug where search returned everything even on no match

---

front50-gcs/src/main/java/com/netflix/spinnaker/front50/model/GcsStorageService.java

fix(google): strip out google.com:, if present, from default bucket name

---

build.gradle

Update spinnaker-dependencies to 0.86.0

---

front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3Config.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/model/S3StorageService.java

If you prefer `ensureBucketExists` does not get called during init that's OK. I filled out that method primarily for Halyard's consumption.

feat(s3): Create specified bucket when it doesn't exist

---

front50-core/front50-core.gradle
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/application/Application.groovy
front50-web/front50-web.gradle
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/AuthorizationSupport.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PermissionsController.groovy

feat(fiat): Updates to new read-only permission model

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/StorageServiceSupport.java

The `Collectors.toMap` method will throw a `DuplicateKeyException` if an item has already been put into the HashMap, causing front50 to crash. Changes this section to use a normal loop that will log & replace the item.
@jeyrschabu PTAL

fix(core): Gracefully handle duplicate key errors during cache refresh

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/config/Front50WebConfig.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PipelineTemplateController.java

Cassandra is deprecated. Will not receive pipeline template support.
@spinnaker/reviewers PTAL

fix(cassandra): Disable Pipeline Template storage capability

---

front50-gcs/src/main/java/com/netflix/spinnaker/front50/model/GcsStorageService.java

fix(google): Log file udpates.

---

front50-cassandra/src/main/groovy/com/netflix/spinnaker/front50/model/application/CassandraApplicationDAO.groovy
front50-cassandra/src/test/groovy/com/netflix/spinnaker/front50/model/application/CassandraApplicationDAOSpec.groovy
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/application/Application.groovy
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/application/ApplicationDAO.groovy

It's a low-value, confusing, misleading field.
(some additional context in https://github.com/spinnaker/orca/pull/1291)

refactor(applications): remove accounts field from applications

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/v2/ApplicationsController.groovy

@veeresh1982 please take for a spin
If successful, this will need to be cherry picked into the 1.1 branch

fix(permissions): Merge permissions for single application config call

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/pipeline/PipelineTemplate.java
front50-core/src/test/groovy/com/netflix/spinnaker/front50/model/pipeline/PipelineTemplateSpec.groovy

@robzienert 
Someone hit this, and I think it's reasonable for a template to have no scopes.

fix(pipeline_templates): don't NPE if template has no scopes

---

build.gradle
front50-core/front50-core.gradle
front50-web/front50-web.gradle
front50-web/src/main/groovy/com/netflix/spinnaker/front50/Main.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/config/Front50WebConfig.groovy

Merging into `boot-upgrade` branch

chore(springBoot): Upgrade to Spring Boot 1.5.4

---

front50-s3/src/main/java/com/netflix/spinnaker/front50/model/S3StorageService.java

This implements https://github.com/spinnaker/halyard/issues/647.

feat(s3): enable S3 bucket versioning

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PipelineTemplateController.java
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/PipelineTemplateControllerSpec.groovy

Foundation work for being able to perform plans on all dependent pipelines during a template update operation. Updates the dependent template work to be recursive as well.
@emjburns

feat(pipeline_template): Get dependent pipeline configs for template id

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PipelineController.groovy

feat(web): adding optional refresh param for listing pipelines

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/application/Application.groovy
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/pipeline/DefaultPipelineDAO.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/pipeline/PipelineDAO.groovy
front50-core/src/test/groovy/com/netflix/spinnaker/front50/model/application/ApplicationModelSpec.groovy
front50-pipelines/src/main/groovy/com/netflix/spinnaker/front50/pipeline/PipelineRepository.groovy
front50-redis/src/main/groovy/com/netflix/spinnaker/front50/redis/RedisPipelineDAO.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PipelineController.groovy

@ajordens @robzienert updating the other endpoint.

feat(web): adding optional refresh param for pipelines by application

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/pipeline/DefaultPipelineDAO.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/pipeline/PipelineDAO.groovy
front50-pipelines/src/main/groovy/com/netflix/spinnaker/front50/pipeline/PipelineRepository.groovy
front50-redis/src/main/groovy/com/netflix/spinnaker/front50/redis/RedisPipelineDAO.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PipelineController.groovy

Reverting to default refresh behavior (true). 
@ajordens @ewiseblatt PTAL

fix(web): change refresh to default behavior

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/ObjectKeyLoader.java

chore(javadoc): fix invalid javadoc character

---

front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3Config.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/model/EventingS3ObjectKeyLoader.java
front50-s3/src/test/groovy/com/netflix/spinnaker/front50/model/EventingS3ObjectKeyLoaderSpec.groovy

Health checks will not be refreshed if you do!

fix(s3): Thou shalt not block the single threaded `taskScheduler`

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/IntentController.java
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/IntentControllerSpec.groovy

@robzienert changing to upsert instead of create and save.

fix(keel): changing controller to upstart

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/intent/DefaultIntentDAO.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/intent/Intent.java
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/IntentController.java
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/IntentControllerSpec.groovy

id is not a uuid, so it must be lowercased in order to correctly invalidate the local cache

fix(intent): lowercasing id

---

front50-azure/src/main/java/com/netflix/spinnaker/front50/model/AzureStorageService.java

Inspired by spinnaker/front50#284

fix(azure): AzureStorageService should throw exception if object not found

---

front50-web/lib/systemd/system/front50.service

Add systemd service configuration for front50.

feat(xenial_builds): Added systemd service configuration for Front50.

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/IntentController.java
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PipelineTemplateController.java

Throwing exception when not supported instead of using `ConditionalOnBean`. We don't want to implement support for storage backends that are no longer supported (like redis and cassandra), so if the storage backend you've chosen is no longer supported you won't be able to use intents or pipeline templates but front50 will still start up. This allows newer features to be optional and front50 to be used without these new features.
This is not new behavior from this PR, I'm just explaining the reasoning here.

fix(pipelineTemplates): throw exception when not supported

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/pipeline/Pipeline.groovy
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/pipeline/TemplateConfiguration.java
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PipelineController.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/PipelineControllerTck.groovy

Adds validation for any pipeline with spinnaker managed pipeline templates. This will ensure the template is available on create or update.
https://github.com/spinnaker/spinnaker/issues/2492

fix(pipelineTemplates): Validate Pipelines with Templates

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/StorageServiceSupport.java

S3 (and possibly others) is eventually consistent when versioning is
enabled.
A stale read is defined as a load that returns an object with an older
`lastModifiedTime`.
It would be useful to know how often this happens in reality.

feat(log): log whenever an object load returns a stale value

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PipelineController.groovy

This will help us easily recover deleted pipelines by printing the id, name, and application.

fix(logs): adding delete log to correlate pipeline name with pipeline id

---

front50-s3/src/main/java/com/netflix/spinnaker/front50/model/S3StorageService.java

Corrects an oopsie on spinnaker/front50#316

fix(s3): Short-circuit needs to be a modifable `List`

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/notification/NotificationDAO.groovy

Add a new notification type bearychat.
This PR is related to [spinnaker/spinnaker#2874](https://github.com/spinnaker/spinnaker/issues/2874)

feat(notification): add bearychat support

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/notification/NotificationDAO.groovy

Add a new notification type Google Chat.
This is part of the issue spinnaker/spinnaker#2936

feat(notification): Add support for Google Chat.

---

front50-gcs/src/main/java/com/netflix/spinnaker/front50/config/GcsConfig.java
front50-gcs/src/main/java/com/netflix/spinnaker/front50/model/GcsStorageService.java
front50-gcs/src/test/groovy/com/netflix/spinnaker/front50/model/GoogleStorageServiceSpec.groovy

fix(gcs): tolerate rate limit errors on timestamp files.

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/StorageServiceSupport.java

For GCS storage, we are currently deciding whether the cache is invalid by comparing a timestamp generated in Java (the time of last refresh) against a timestamp generated by GCS (the time of last update). This can lead to issues with fast read-update-read operations when the two systems don't
have perfectly synchronized clocks. Let's keep track of the last timestamp we actually read from cloud storage, and use that to determine whether the cache should be invalidated.

fix(core): Fix race condition in cache invalidation

---

front50-gcs/src/main/java/com/netflix/spinnaker/front50/model/GcsStorageService.java

feat(google): Add GCS statusCodes to metrics

---

build.gradle
front50-gcs/src/main/java/com/netflix/spinnaker/front50/model/GcsStorageService.java

Removes the indirect dependency on clouddriver-core
Related to https://github.com/spinnaker/clouddriver/pull/2981

refactor(gcs): Update doRetry and bump clouddriver version

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PermissionsController.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/ServiceAccountsController.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/SnapshotsController.groovy

Enable /permissions, /serviceAccounts, and /snapshots for Oracle storage.

fix(persistentStorage/oracle): add support for permission etc.

---

front50-web/front50-web.gradle
front50-web/src/main/groovy/com/netflix/spinnaker/front50/config/GraphQLSchemaConfiguration.java
front50-web/src/main/groovy/com/netflix/spinnaker/front50/graphql/JsonScalarType.java
front50-web/src/main/groovy/com/netflix/spinnaker/front50/graphql/datafetcher/PipelinesDataFetcher.java
front50-web/src/main/groovy/com/netflix/spinnaker/front50/graphql/telemetry/SpectatorGraphQLInstrumentation.java
front50-web/src/main/resources/graphql/pipelineConfig.graphqls

⚠️ This isn't intended for anything more than an exhibit.
We're seeing performance issues elsewhere and suspect we've gotten to the point where we're just transferring too much data out of front50 too often. GraphQL seems a logical choice over something like more endpoints or query params to change response payloads.
I'd say I'm... 10% sure what I'm doing at this point, but is this intriguing enough to pursue?
@spinnaker/netflix-reviewers

wip(web): GraphQL

---

front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3Config.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3Properties.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/model/S3StorageService.java

This is the same PR as #364 for release 1.10 branch.

fix(s3): Add control over nb of objects retrieved per batch (maxKeys)

---

.travis.yml
README.md
front50-web/front50-web.gradle
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/NotificationControllerTck.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/PipelineControllerTck.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/StrategyControllerTck.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/v2/ApplicationsControllerTck.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/v2/ProjectsControllerTck.groovy
front50-web/src/test/resources/log4j.properties

This fixes the s3 TCK that are in the web project. I also updated CI to be able to run the tests at part of this.

 fix(s3/web): Fix s3 TCK tests

---

front50-oracle/front50-oracle.gradle

https://github.com/spinnaker/clouddriver/pull/3214

chore(oracle/dependency): upgrade oracle oci sdk version to 1.3.2

---

front50-oracle/src/main/java/com/netflix/spinnaker/front50/config/OracleProperties.java
front50-oracle/src/main/java/com/netflix/spinnaker/front50/model/OracleStorageService.java

Cherry-pick the fix (#379) into Spinnaker 1.10 release so that it would fix the bucket creation problem in oracle storage.

fix(storage/oracle): add private key passphrase

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/notification/NotificationDAO.groovy

Needed to support https://github.com/spinnaker/echo/pull/417

feat(notifications): Adds pubsub notification type

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/application/Application.groovy

Some people prefer `enabled` flags to `disabled` flags so let's make those people happy

feat(trafficguards): set enabled flag on traffic guards; default to true

---

front50-gcs/src/main/java/com/netflix/spinnaker/front50/config/GcsConfig.java
front50-gcs/src/main/java/com/netflix/spinnaker/front50/model/GcsStorageService.java

fix(gcs): Increased default timeout with config override.

---

front50-web/front50-web.gradle

Cherry-pick the fix (https://github.com/spinnaker/front50/pull/397) into Spinnaker 1.11 release.
Related PR for clouddriver is https://github.com/spinnaker/clouddriver/pull/3306.

Fix missing jars release 1.11.x

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/application/Application.groovy

Did some actual testing this time around

fix(core): correctly save traffic guard configurations

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/DeliveryController.java
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/DeliveryControllerSpec.groovy

What should have been my final commit on https://github.com/spinnaker/front50/pull/455/commits :D

fix(delivery): update endpoints to use deliveries

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/ServiceAccountsController.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/ServiceAccountsControllerSpec.groovy

To ensure that Fiat immediately resolves new permissions involving the newly created service account, we explicitly call Fiat's sync API. We also need to invalidate Front50's in memory cache of fiat permissions. Otherwise, Front50 will continue to use the stale cache to make authorization decisions. 
e.g. if we create a service account and then immediately create a pipeline with this service account, the pipeline save will fail since the current user will not have access to the service account.
Fixes https://github.com/spinnaker/spinnaker/issues/3966

fix(authz): Invalidate local Fiat cache on service acct creation.

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/application/Application.groovy

If a user has deleted an application, and we want to restore it, it can be really difficult to track down pipeline configs. This should help?

feat(core): add detailed logging when deleting application components

---

build.gradle
front50-azure/front50-azure.gradle
gradle/init-publish.gradle

https://github.com/spinnaker/spinnaker/issues/3997

fix(build): make gradle use https

---

front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3BucketProperties.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3Config.java

feat(s3): Make pathStyleAccess configurable

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/v2/ApplicationsController.groovy

We have a request from some of our API users to include permissions in the response from `/applications`, which seems reasonable since it's a field that is updated via the `updateApplication` task in Orca.
Happy to put it behind a parameter if folks feel strongly that it should be optionally included, as it will increase payload size a little.

feat(applications): include permissions from /applications list endpoint

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/pipeline/PipelineTemplate.java
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/V2PipelineTemplateController.java

Fixes front50 caching performance due to id mismatches.

fix(MPTv2): Fix tag storage for pipeline config caching.

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/v2/ApplicationsController.groovy

fix(permissions): fix for #513

---

front50-web/front50-web.gradle

Prereq for spinnaker/kork#273 merge

chore(dependencies): ensure direct dependency on kork-secrets-aws

---

front50-azure/src/main/java/com/netflix/spinnaker/front50/model/AzureStorageService.java

The bug is related to [this commit](https://github.com/spinnaker/echo/pull/518/files#diff-e714a7d17e98672cdf84b7456c4b1ece)
We found that after we change the server group configuration in **Deploy stage** in **pipeline** and then manually trigger the execution, it always use old configuration.
**echo** will call `@GET("/pipelines/{pipelineId}/history?limit=1")` to get the latest version of pipeline. Then the **listObjectVersions** in **AzureStorageService** will handle the request and fetch one pipeline from Azure storage. However, the sdk will fetch the oldest one instead of latest one. That's why the new configuration doesn't take effect.

fix(provider/azure): Fix when fetching multiple versions of pipeline, it always fetches old version.

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/ObjectType.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/StorageServiceSupport.java
front50-web/src/main/groovy/com/netflix/spinnaker/front50/Main.groovy

This PR reflects a small bit of cleanup in support of adding SQL
support.

fix(core): Publicly expose attributes of `ObjectType`

---

front50-web/front50-web.gradle
front50-web/src/main/groovy/com/netflix/spinnaker/front50/Main.groovy

In boot2, location overrides rather than adds to the default config locations.

fix(core): Switch location to additional-location

---

front50-oracle/front50-oracle.gradle
front50-web/front50-web.gradle

chore(front50/oracle): Get the Oracle API jar from Maven.

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/StorageServiceSupport.java
front50-web/src/main/groovy/com/netflix/spinnaker/front50/config/Front50WebConfig.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/config/ItemDAOHealthIndicator.groovy

This mimics what `orca` is doing.

fix(core): Provide a multi-thread capable `taskScheduler`

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PermissionsController.groovy

This is only a problem as the `redis` support in `front50` does not
have support for all DAO interfaces.
Eventually i'd like to see `redis` deprecated and removed.

fix(web): Better handling when `ApplicationPermissionDAO` does not exist

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/AuthorizationSupport.groovy

chore(logging): make access denies log more stronger

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/v2/ApplicationsController.groovy
gradle.properties

fix(fiat-api): fix usage of removed method from Permissions

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/v2/ApplicationsController.groovy

Typo in application creation restriction

fix(authorization): typo in application creation restriction

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/v2/ApplicationsController.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/v2/ApplicationsControllerTck.groovy
gradle.properties

Should fix https://github.com/spinnaker/spinnaker/issues/5063

fix(authorization): Sync roles after an application is created

---

gradle.properties

applies fiatVersion change from #630

fix(authorization): update fiatVersion to fix canCreate

---

Dockerfile.java8
Dockerfile.ubuntu-java8

Part of the [Java 11 migration effort](https://github.com/spinnaker/community/blob/master/rfc/java11.md).

chore(java11): Switch the default containers to use Java 11.

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/pluginartifact/PluginArtifactService.java
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PluginArtifactController.java

Turns out, this will be useful to satisfy pf4j's `UpdateRepository`:
https://github.com/pf4j/pf4j-update/blob/master/src/main/java/org/pf4j/update/UpdateRepository.java#L49

fix(plugins): Add GET by pluginId

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/ApplicationPermissionsService.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/listeners/ChaosMonkeyEventListener.java
front50-core/src/test/groovy/com/netflix/spinnaker/front50/listeners/ChaosMonkeyEventListenerSpec.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PermissionsController.groovy

Revert "fix(permissions): Apply chaos monkey permissions on application update permissions event"

---

front50-core/front50-core.gradle
front50-core/src/main/groovy/com/netflix/spinnaker/front50/validator/HasCanonicalPluginIdValidator.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/validator/HasValidRequiresFieldsValidator.java

Depends on https://github.com/spinnaker/kork/pull/480

fix(plugins): Use kork-plugins VersionRequirementsParser and CanonicalPluginId in plugin info validators

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/config/PluginBinaryCacheConfiguration.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/plugininfo/PluginInfo.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/plugininfo/PluginInfoRepository.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/plugins/CachingPluginBinaryStorageService.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/plugins/PluginBinaryAlreadyExistsException.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/plugins/PluginBinaryStorageService.java
front50-core/src/test/groovy/com/netflix/spinnaker/front50/plugins/CachingPluginBinaryStorageServiceSpec.groovy
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3Config.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3EventingConfiguration.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3PluginBinaryServiceConfiguration.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3StorageServiceConfiguration.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/plugins/S3PluginBinaryStorageService.java
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PluginBinaryController.java

Forgot to make this feature work when S3 is not enabled. 🤦‍♂

feat(plugins): Plugin binary store service (again)

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/plugininfo/PluginInfoService.java
front50-core/src/test/groovy/com/netflix/spinnaker/front50/model/plugininfo/PluginInfoServiceSpec.groovy

-- Upsert release nodes in the plugin info w/o replacing the old release information (which we require to rollback to the previous version if needed)

Plugin upsert fix

---

.github/workflows/build.yml
.github/workflows/pr.yml
.github/workflows/release.yml
.github/workflows/release_info.sh
build.gradle
front50-bom/front50-bom.gradle
front50-web/front50-web.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties

updates to gradle 6.3
updates to kotlin 1.3.70
updates github actions workflows for new release flags

chore(build): update to newer spinnaker project plugin

---

front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/v2/ApplicationsController.java
front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/v2/ProjectsController.java

fix(web): Regressions from Groovy migration

---

front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/PipelineController.java

More fallout from groovy refactor.

fix(web): NPE on pipelines without type

---

front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/PipelineController.java

Front50 can potensially crash when trying to save a pipeline because `regenerateCronTriggerIds` (if set) is already a boolean, and can't be cast to a String.
Regression introduced in #841.

fix(pipeline): Fix regression in Java conversion of PipelineController

---

front50-core/front50-core.gradle
front50-core/src/main/java/com/netflix/spinnaker/front50/config/EchoConfiguration.java
front50-core/src/main/java/com/netflix/spinnaker/front50/echo/EchoService.java
front50-core/src/main/java/com/netflix/spinnaker/front50/echo/Event.java
front50-core/src/main/java/com/netflix/spinnaker/front50/echo/Notification.java

This is in prep for moving plugin events from igor to front50

feat(echo): Add dependency on echo

---

front50-azure/front50-azure.gradle
front50-core/src/main/java/com/netflix/spinnaker/front50/validator/HasValidRequiresFieldsValidator.java
front50-core/src/test/groovy/com/netflix/spinnaker/front50/validator/HasValidRequiresFieldsValidatorSpec.groovy
front50-gcs/front50-gcs.gradle
front50-s3/front50-s3.gradle
gradle.properties

fixes some breaking changes and dependency updates from latest kork release

fix(kork): updates to kork 7.54.0

---

front50-sql/src/main/kotlin/com/netflix/spinnaker/front50/model/CompositeStorageService.kt
front50-sql/src/test/kotlin/com/netflix/spinnaker/front50/model/CompositeStorageServiceTests.kt

-- Adding  missing(`storeObjects` and `recover`)operations to composite storage service

fix(misc): add bulk store api and recover api for composite storage impl

---

front50-migrations/src/main/java/com/netflix/spinnaker/front50/migrations/DeleteDanglingServiceAccountsMigration.java
front50-migrations/src/main/java/com/netflix/spinnaker/front50/migrations/RunAsUserToPermissionsMigration.java
front50-sql/src/main/kotlin/com/netflix/spinnaker/front50/model/CompositeStorageService.kt
front50-sql/src/main/kotlin/com/netflix/spinnaker/front50/model/SqlStorageService.kt
front50-sql/src/main/kotlin/com/netflix/spinnaker/front50/model/sql/Jooq.kt
front50-sql/src/test/kotlin/com/netflix/spinnaker/config/CompositeStorageServiceConfigurationTests.kt
front50-sql/src/test/kotlin/com/netflix/spinnaker/front50/model/SqlStorageServiceTests.kt
gradle.properties

This includes updates to google-java-format and ktlint, so requires some
formatting changes. These were made with a simple `./gradlew spotlessApply`.

chore(spotless): upgrade spinnaker gradle plugin

---

front50-oracle/front50-oracle.gradle
front50-oracle/src/main/java/com/netflix/spinnaker/front50/model/OracleStorageService.java

fix(provider/Oracle): Cache issue related to Oracle Object Storage #886

---

front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/PipelineController.java

feat(pipeline): (optionally) validate that a saved pipeline is not stale

---

front50-oracle/front50-oracle.gradle
front50-oracle/src/main/java/com/netflix/spinnaker/front50/model/OracleStorageService.java

fix(provider/Oracle): Cache issue related to Oracle Object Storage (bp #886)

---

front50-core/src/main/java/com/netflix/spinnaker/front50/config/EchoConfiguration.java

- Use service client api instead of using Retrofit api directly.

fix(client): Move to retrofit service client api

---

front50-migrations/src/main/java/com/netflix/spinnaker/front50/migrations/MigrationRunner.java

- Conditionally enabling migration runner

fix(misc): Conditionally enable migration runner

---

front50-core/src/main/java/com/netflix/spinnaker/front50/config/ChaosMonkeyEventListenerConfigurationProperties.java
front50-core/src/test/groovy/com/netflix/spinnaker/front50/listeners/ChaosMonkeyApplicationEventListenerSpec.groovy
front50-core/src/test/groovy/com/netflix/spinnaker/front50/listeners/ChaosMonkeyApplicationPermissionEventListenerSpec.groovy
front50-migrations/front50-migrations.gradle
front50-migrations/src/main/java/com/netflix/spinnaker/front50/migrations/RemoveChaosMonkeyUserMigration.java
front50-migrations/src/test/groovy/com/netflix/spinnaker/front50/migrations/RemoveChaosMonkeyUserMigrationSpec.groovy

Puts us on a path towards deleting the chaos monkey even listener code too.  Tweaked the config a bit so we can roll this migration out in a simple way.

migration(chaosmonkey): Remove chaos monkey user migration

---

build.gradle
front50-api-tck/front50-api-tck.gradle
gradle.properties
gradle/kotlin.gradle

chore(kotlin): move to new kotlin version and upgrade kork

---

front50-core/src/main/java/com/netflix/spinnaker/front50/model/StorageServiceSupport.java
front50-web/front50-web.gradle
front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/PipelineController.java
front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/StrategyController.java
front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/v2/ApplicationsController.java
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/NotificationControllerTck.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/PipelineControllerTck.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/StrategyControllerTck.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/v2/ApplicationsControllerTck.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/v2/ProjectsControllerTck.groovy
front50-web/src/test/resources/log4j.properties
front50-web/src/test/resources/logback.xml

Of course the S3-backed tests never actually ran
and the migration to SQL exposed a handful of
minor bugs/inconsistencies.

fix(web): Migrate controller tests from S3 to SQL

---

front50-sql/src/test/kotlin/com/netflix/spinnaker/front50/model/TestDatabase.kt
gradle.properties

Couple of code changes required by latest version of JOOQ

Fix JOOQ bump from Kork

---

front50-bom/front50-bom.gradle
front50-core/front50-core.gradle
front50-migrations/front50-migrations.gradle
front50-web/front50-web.gradle
gradle.properties

chore(deps): update fiat to 1.27.0, use new maven coordinates

---

front50-azure/src/main/java/com/netflix/spinnaker/front50/model/AzureStorageService.java

This is an attempt to fix:
- https://github.com/spinnaker/spinnaker/issues/5892
- https://github.com/spinnaker/spinnaker/issues/6218
The following PRs attempted to address this issue, and appear to be
orphaned:
- https://github.com/spinnaker/front50/pull/900 - Failing checks.
- https://github.com/spinnaker/front50/pull/1002 - Fixing more than one
thing.  Should be two (2) PRs.

fix(provider/azure): Stop making containers public

---

front50-sql/src/main/resources/db/changelog-master.yml
front50-sql/src/main/resources/db/changelog/20230420-add-last-modified-at-indexes.yml

to speed up SqlStorageService.loadObjectsNewerThan and other queries involving last_modified_at.

perf(sql): add index on last_modified_at

---

front50-core/src/main/java/com/netflix/spinnaker/front50/model/StorageServiceSupport.java
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/PipelineControllerTck.groovy

and try to prevent them getting to the data store in the first place by rejecting them in StorageServiceSupport.update.

fix(core): tolerate items with null ids

---

.github/workflows/build.yml
.github/workflows/pr.yml
.github/workflows/release.yml
Dockerfile.compile
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/PipelineControllerTck.groovy
gradle.properties

Compile to Java 11 bytecode using JDK 17.
Reference: https://github.com/spinnaker/igor/pull/1198

chore(build): enable cross compilation plugin for Java 17
