front50-web/front50-web.gradle

Commit 7ca8419 broke front50 in our testing, triggering the following exception every time we try to create an application:
java.lang.IllegalStateException: Instrumentation is not set; Jamm must be set as -javaagent
Looks like jvmArgs accepts an array instead of a string, so changing it to pass in a list of arguments rather than a single string fixed it for us.

Fix errors in front50 caused by jamm not being a part of -javaagent

---

front50-cassandra/src/main/groovy/com/netflix/spinnaker/front50/model/application/CassandraApplicationDAO.groovy
front50-cassandra/src/test/groovy/com/netflix/spinnaker/front50/model/application/CassandraApplicationDAOSpec.groovy
front50-core/src/main/groovy/com/netflix/spinnaker/front50/config/ApplicationDAOProviderHealthIndicator.groovy
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/application/Application.groovy
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/application/ApplicationDAO.groovy
front50-core/src/test/groovy/com/netflix/spinnaker/front50/config/ApplicationDAOProviderHealthIndicatorSpec.groovy
front50-core/src/test/groovy/com/netflix/spinnaker/front50/model/application/ApplicationModelSpec.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/ApplicationsController.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/ApplicationsControllerSpec.groovy

Attempting to define the actual, reliably present fields on an application as:
* name
* description
* email
* accounts
* createTs
* updateTs
All other fields are optional, which will allow users to customize the fields they want to include - we can get rid of things like "pdApiKey" in the OSS world, and add it by exposing the field in the UI via the netflix module.
~~We are still stuck with Strings everywhere, so complex objects would need to be passed in as String from the UI, then parsed when they come back to the UI, which is fine.~~
Complex objects can also be stored, since we're using an ObjectMapper to convert the details to a string for storage. You can also store numbers, booleans, nested objects, etc. without needing to convert them back and forth to/from strings.
It's possible …

declare minimal app properties, allow all others

---

front50-cassandra/src/main/groovy/com/netflix/spinnaker/front50/model/application/CassandraApplicationDAO.groovy

We've been storing these fields as Strings, so we should update any existing applications to use Booleans, as that is what the UI sends in.
We'll need to migrate Netflix applications with a different script, since we (okay, I) already pushed the previous changes without this migration to production.
@duftler Please review.

migrate platformHealth* flags to booleans

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/application/ApplicationDAO.groovy
front50-pipelines/src/main/groovy/com/netflix/spinnaker/front50/pipeline/StrategyRepository.groovy
front50-s3/src/main/java/com/netflix/spinnaker/front50/model/S3Support.java
front50-web/src/main/groovy/com/netflix/spinnaker/front50/config/Front50WebConfig.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/config/ItemDAOHealthIndicator.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/config/ItemDAOHealthIndicatorSpec.groovy

- S3 just ensures it's refreshed itself in the past 45s
- Cassandra* executes a query
* Only CassandraApplicationDAO executes a query, the other DAOs just return true (just tests Cassandra connectivity which should be the same regardless of DAO)

Include each ItemDAO in the health check

---

front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3Config.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/model/S3PipelineDAO.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/model/S3PipelineStrategyDAO.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/model/S3Support.java
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/NotificationController.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/ApplicationsControllerTck.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/NotificationControllerTck.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/PipelineControllerTck.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/StrategyControllerTck.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/v2/ProjectsControllerTck.groovy

- update/delete now writes "last-modified.json" containing a modification timestamp
- all() will now check and only refresh() if a recent modification is detected, avoids fetching all object metadata which can be an expensive operation on larger folders (pipelines/applications)
- NotificationController no longer repeatedly loads the global notification config

S3 DAOs should refresh only when a modification is detected

---

front50-s3/src/main/java/com/netflix/spinnaker/front50/model/S3PipelineDAO.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/model/S3Support.java

- Tested via a loop of create pipeline -> delete pipeline -> query for pipelines by application
- Fixed the serialization warnings by setting MD5 and Content-Length on ObjectMetadata

'lastRefreshedTime' should be calculated pre-fetchAll not post-fetchAll

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/application/Application.groovy

On application save: https://github.com/spinnaker/front50/blob/master/front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/application/Application.groovy#L171 `originalApplication` is passed as `null`, causing the error reporting to fail.
@spinnaker/netflix-reviewers PTAL

core: NPE thrown while reporting save error

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PipelineController.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/StrategyController.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/PipelineControllerTck.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/StrategyControllerTck.groovy

prevent creation of pipelines with duplicate names

---

front50-gcs/front50-gcs.gradle
front50-gcs/src/main/java/com/netflix/spinnaker/front50/config/GcsConfig.java
front50-gcs/src/main/java/com/netflix/spinnaker/front50/model/ApplicationBucketDAO.java
front50-gcs/src/main/java/com/netflix/spinnaker/front50/model/BucketDAO.java
front50-gcs/src/main/java/com/netflix/spinnaker/front50/model/GcsStorageService.java
front50-gcs/src/main/java/com/netflix/spinnaker/front50/model/NotificationBucketDAO.java
front50-gcs/src/main/java/com/netflix/spinnaker/front50/model/PipelineBucketDAO.java
front50-gcs/src/main/java/com/netflix/spinnaker/front50/model/PipelineStrategyBucketDAO.java
front50-gcs/src/main/java/com/netflix/spinnaker/front50/model/ProjectBucketDAO.java
front50-gcs/src/main/java/com/netflix/spinnaker/front50/model/StorageService.java
front50-gcs/src/test/groovy/com/netflix/spinnaker/front50/model/ApplicationBucketDAOSpec.groovy
front50-gcs/src/test/groovy/com/netflix/spinnaker/front50/model/GoogleStorageServiceSpec.groovy
front50-web/front50-web.gradle

@ajordens 
This is another take on the previous GCS PR but assumes a refactoring.
I put the refactoring in the google-gcs package here, because I'm not sure where to put it and want to run it by you before pursuing it further. I left S3 alone, but it is based on what you did so should be straight forward to refactor.
The design uses a base BucketDAO class with the item subclasses as before, except that you inject a StorageService into the BucketDAO constructor where the StorageService is specialized for the underlying service implementation.
In the BucketDAO I cut out this block https://github.com/spinnaker/front50/blob/master/front50-s3/src/main/java/com/netflix/spinnaker/front50/model/S3Support.java#L256
because it seemed superfluous. I suspect it really is not and there is an extra bit …

Added Google Cloud Storage alternative to Cassandra.

---

front50-gcs/src/main/java/com/netflix/spinnaker/front50/model/PipelineBucketDAO.java
front50-gcs/src/test/groovy/com/netflix/spinnaker/front50/model/PipelineBucketDAOSpec.groovy
front50-redis/src/test/groovy/com/netflix/spinnaker/front50/redis/RedisPipelineDAOSpec.groovy
front50-s3/src/main/java/com/netflix/spinnaker/front50/model/S3PipelineDAO.java
front50-s3/src/test/groovy/com/netflix/spinnaker/front50/model/S3PipelineDAOSpec.groovy
front50-test/src/main/groovy/com/netflix/spinnaker/front50/pipeline/PipelineDAOSpec.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PipelineController.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/PipelineControllerTck.groovy

Saving a pipeline with no `application` property means we can never retrieve any pipelines until the database gets cleaned up. This is quite bad.
PTAL @ajordens

validate pipelines have applications and names

---

front50-gcs/src/main/java/com/netflix/spinnaker/front50/model/BucketDAO.java
front50-gcs/src/main/java/com/netflix/spinnaker/front50/model/GcsStorageService.java
front50-gcs/src/test/groovy/com/netflix/spinnaker/front50/model/GoogleStorageServiceSpec.groovy

Also, delete (purge) old versions of the timestamp files since they are particularly
volatile and it doesnt make sense version them.

Dont log full GCS errors because it's noisy given implied applications.

---

front50-web/front50-web.gradle

This change will fix problems where logrotate ignores
/etc/logrotate.d/front50 due to 'bad file mode.'
For Spinnaker issue [#904](https://github.com/spinnaker/spinnaker/issues/904)

Update logrotate film permissions

---

front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3Config.java

without region set S3 requests get a redirect from the generic s3.amazonaws.com to the appropriate regional endpoint. this works but it's an extra hop
@spinnaker/netflix-reviewers PTAL

optionally specify region on AmazonS3 client

---

front50-cassandra/src/main/groovy/com/netflix/spinnaker/front50/model/application/CassandraApplicationDAO.groovy
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/application/Application.groovy
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/application/ApplicationDAO.groovy
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/application/ApplicationPermissionDAO.java
front50-gcs/src/main/java/com/netflix/spinnaker/front50/config/GcsConfig.java
front50-gcs/src/main/java/com/netflix/spinnaker/front50/model/ApplicationBucketDAO.java
front50-gcs/src/main/java/com/netflix/spinnaker/front50/model/ApplicationPermissionBucketDAO.java
front50-gcs/src/main/java/com/netflix/spinnaker/front50/model/GcsStorageService.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3Config.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/model/S3ApplicationPermissionDAO.java
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PermissionsController.groovy

New endpoint will be used by Fiat when starting up to load applications and periodically update its cache.  POST/PUT endpoints can be used by Orca when new applications are created.
Deprecates CassandraDAO since NFLX is no longer using it and we're encouraging new customers to go the GCS/S3 bucket route.
@ajordens @cfieber @jtk54 @duftler PTAL.

Adds ApplicationPermission model object, DAO for GCS/S3, and controller.

---

front50-gcs/src/main/java/com/netflix/spinnaker/front50/config/GcsConfig.java
front50-gcs/src/main/java/com/netflix/spinnaker/front50/model/GcsStorageService.java
front50-gcs/src/test/groovy/com/netflix/spinnaker/front50/model/GoogleStorageServiceSpec.groovy

Fixes https://github.com/spinnaker/spinnaker/issues/1002. Buckets already created cannot have their location changed - you must move the data, delete it and have Front50 recreate the bucket. See https://cloud.google.com/storage/docs/managing-buckets#manage-class-location
@ewiseblatt @duftler @lwander PTAL
CC: @leelasharma

Adds ability to specify location of GCS auto-created bucket.

---

front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3Config.java

- Ended up using a `String` and applying Integer::parseInt when it's used

Fix issue deserializing into `proxyPort`

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/snapshot/Snapshot.groovy
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/snapshot/SnapshotDAO.groovy
front50-gcs/src/main/java/com/netflix/spinnaker/front50/config/GcsConfig.java
front50-gcs/src/main/java/com/netflix/spinnaker/front50/model/SnapshotBucketDAO.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3Config.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/model/S3SnapshotDAO.java
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/SnapshotsController.groovy

Added an infrastructure definition model and DAO for saving the state of the infrastructure. Created a controller endpoint for saving infrastructure to a gcs bucket and querying for previous versions. To test, gcs must be enabled in front50.yml with the necessary fields populated for finding a bucket. PTAL @lwander @duftler

provider/google: added support for saving infrastructure definitions to gcs buckets

---

front50-gcs/src/main/java/com/netflix/spinnaker/front50/model/GcsStorageService.java
front50-gcs/src/test/groovy/com/netflix/spinnaker/front50/model/GoogleStorageServiceSpec.groovy

Also attempt an update before an insert since it is far less likely to fail.

Add timestamp marker files to avoid future 404 error noise

---

front50-cassandra/src/main/groovy/com/netflix/spinnaker/front50/model/project/CassandraProjectDAO.groovy
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/application/Application.groovy
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/project/ProjectDAO.groovy
front50-core/src/test/groovy/com/netflix/spinnaker/front50/model/application/ApplicationModelSpec.groovy
front50-gcs/src/main/java/com/netflix/spinnaker/front50/model/ProjectBucketDAO.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/model/S3ProjectDAO.java
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/ApplicationsController.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/ApplicationsControllerTck.groovy

@ajordens alternative I could see was to implement this as an `ApplicationEventListener`, but we'd have to include the `projectDAO` as one of the properties in the copy of the `Application` object.
Also not sure if we should be deleting the project, although it's probably a safe bet, since someone has explicitly gone in and deleted every application in the project at that point.

clean up projects when deleting an application

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/snapshot/Snapshot.groovy

I changed infrastructure to be saved as a map rather than a string. This makes it easier to parse the infrastructure into proper format for the diff view in deck. @lwander @danielpeach

provider/core: Snapshot infrastructure saved as map rather than string

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/config/Front50WebConfig.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/v2/ApplicationsController.groovy

- Reverted to using {applicationName:.+} to match url parameters containing a dot

Fix an issue related to parameter names in V2 Application API

---

front50-redis/src/main/groovy/com/netflix/spinnaker/front50/redis/RedisConfig.groovy
front50-web/config/front50.yml

The Redis backend defaulted to localhost:6379. This PR enables specifying an arbitrary Redis host/port.

Enable configuration values for Redis host and port

---

front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3Config.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/model/ReadOnlyModeException.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/model/S3StorageService.java

Adds configuration for a failover bucket and region for S3 to support internal availability stories. When `spinnaker.s3.failover.enabled = true`, the application will connect to the configured failover bucket, as well as set front50 into a read-only mode. 
For the foreseeable future, this flag will be manually managed and require service restart to flip.
@spinnaker/netflix-reviewers PTAL

Adding s3 bucket failover configuration and readonly mode

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PipelineController.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/StrategyController.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/PipelineControllerTck.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/StrategyControllerTck.groovy

- Removed `move` endpoint for pipeline/strategy rename in favor of the update endpoint
- spring security annotated the update endpoint for good measure

Cleaning out unused rename endpoint for pipeline & strategy

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/StorageServiceSupport.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/application/DefaultApplicationDAO.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/application/DefaultApplicationPermissionDAO.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/notification/DefaultNotificationDAO.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/pipeline/DefaultPipelineDAO.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/pipeline/DefaultPipelineStrategyDAO.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/project/DefaultProjectDAO.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/serviceaccount/DefaultServiceAccountDAO.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/snapshot/DefaultSnapshotDAO.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/tag/DefaultEntityTagsDAO.java
front50-gcs/src/main/java/com/netflix/spinnaker/front50/config/GcsConfig.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3Config.java
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/NotificationControllerTck.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/PipelineControllerTck.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/StrategyControllerTck.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/v2/ApplicationsControllerTck.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/v2/ProjectsControllerTck.groovy

increased health check timeout to 90s and fail if a poll interval larger than that is requested
instrumented StorageServiceSupport to add
`storageServiceSupport.cacheAge` gauge
`storageServiceSupport.cacheRefreshTime` timer

fix health indicators for ItemDAOs

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/tag/EntityTags.groovy

@ajordens PTAL
I tried removing the top level `lastModified` and `lastModifiedBy` fields, but those are required to satisfy the `Timestamped` interface, which is required by `StorageServiceSupport` class, so left them in.

include tagsMetadata in EntityTags object

---

front50-web/config/front50.yml

Spring Boot has a builtin RedisHealthCheck. It must be disabled if redis support is also disabled.
Resolves #1018

redis: Make health checks conditional

---

front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3BucketProperties.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3Config.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3Properties.java

This allows alternative S3 implementations such as Minio to be used with Front50.

Allow configurable S3 endpoint

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/StorageServiceSupport.java
front50-gcs/src/main/java/com/netflix/spinnaker/front50/config/GcsConfig.java
front50-gcs/src/main/java/com/netflix/spinnaker/front50/model/GcsStorageService.java
front50-gcs/src/test/groovy/com/netflix/spinnaker/front50/model/GoogleStorageServiceSpec.groovy

@cfieber 
I added more instrumentation around front50 cache management because it is a sensitivity point for performance and critical point for the accumulation of knowledge.
I am double counting refreshes only because it is easier that way. All refreshes use your original timer (I changed the implementation a little to be consistent with the others but am happy to change it back. Originally I made the change because I wasnt seeing the objectType breakout but that turned out to be a different issue. In simplifying that, the recorded time is going to be slightly less accurate because it includes updating the atomic reference. However given the latency of network calls and insignificant critical section on that lock, the difference is going to be negligable.
The second set of counts …

Refined metrics around cache maintainence.

---

front50-s3/front50-s3.gradle

- This will include clouddriver's changes requiring ssh keys to connect to bastion

Bumping clouddriver's version

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/StorageService.java
front50-gcs/src/main/java/com/netflix/spinnaker/front50/model/GcsStorageService.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/model/S3StorageService.java

No sense in having an API we don't use.
@spinnaker/reviewers @scotmoor  PTAL

Removing unused loadObjectVersion storage API

---

front50-azure/src/main/java/com/netflix/spinnaker/front50/config/AzureStorageConfig.java
front50-azure/src/main/java/com/netflix/spinnaker/front50/config/AzureStorageProperties.java
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PermissionsController.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/ServiceAccountsController.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/SnapshotsController.groovy

'spinnaker.azure.enabled' conflicted with the environment variable used for the Azure cloudprovider config. Since azure storage can be used with other providers (like Kubernetes) we want the names to be independent.

Rename azure storage to azs

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/v2/EntityTagsController.groovy

Allows API users to submit multiple tags instead of having to make individual calls for each tag.
(cc @tratzlaff)

(tagging) allow batch update of entity tags

---

front50-s3/front50-s3.gradle
front50-web/front50-web.gradle

front50-nflx is pulling in a newer version of AWS SDK transitively and breaking Front50 on startup. I'm trying to upgrade to the newer spinnaker-dependencies version that will bring in the same AWS version here but it also brings in a newer version of `clouddriver-google-common`.
Also a few things weren't using spinnaker-dependencies when it seems like they should.

try to reconcile dependencies

---

front50-azure/src/main/java/com/netflix/spinnaker/front50/config/AzureStorageConfig.java
front50-azure/src/main/java/com/netflix/spinnaker/front50/config/AzureStorageProperties.java
front50-azure/src/main/java/com/netflix/spinnaker/front50/model/AzureStorageService.java

For a few reasons:
1. Simplify the config
2. Match the folder structure for other providers, which are only 2 levels deep not 3 (in front50.yml, s3.bucket == azs.storageAccountName and s3.rootFolder == azs.storageContainerName)
3. Fix a bug where the 'last_modified' files were stored at the container level and everything else was stored at the (now removed) rootFolder level. Now everything is at the container level.

Remove rootFolder from AZS config

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/v2/EntityTagsController.groovy

Nothing major here:
* adding an endpoint to get all tags for a list of `entityId`s
* returning the results from `/batchUpdate` POSTs so we can take advantage of that endpoint in Clouddriver

entityTags: add findAllById endpoint, return tags on batchUpdate

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/tag/EntityTags.groovy

The idea being that tag name's could be re-used across namespaces, either
intentionally or accidentally.
Permissions / restrictions could also be applied to namespaces vs. individual
tag names.

Introduce a new `namespace` attribute to `EntityTag`

---

front50-web/front50-web.gradle
front50-web/src/main/groovy/com/netflix/spinnaker/front50/config/Front50WebConfig.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PermissionsController.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/ServiceAccountsController.groovy

This is an example of what needs to be done in the rest of the non-Gate components that utilize the Fiat API module - basically a version bump + adding `@EnableFiatAutoConfig`.
@cfieber @jtk54 - PTAL.
Tests won't pass until spinnaker/fiat#154 is submitted and released.

chore(fiat): Bumps Fiat API, adding EnableFiatAutoConfig annotation

---

front50-cassandra/src/main/groovy/com/netflix/spinnaker/front50/model/application/CassandraApplicationDAO.groovy
front50-cassandra/src/main/groovy/com/netflix/spinnaker/front50/model/project/CassandraProjectDAO.groovy
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/ItemDAO.groovy
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/StorageServiceSupport.java
front50-pipelines/src/main/groovy/com/netflix/spinnaker/front50/pipeline/PipelineRepository.groovy
front50-pipelines/src/main/groovy/com/netflix/spinnaker/front50/pipeline/StrategyRepository.groovy
front50-redis/src/main/groovy/com/netflix/spinnaker/front50/redis/RedisApplicationDAO.groovy
front50-redis/src/main/groovy/com/netflix/spinnaker/front50/redis/RedisPipelineDAO.groovy
front50-redis/src/main/groovy/com/netflix/spinnaker/front50/redis/RedisPipelineStrategyDAO.groovy
front50-redis/src/main/groovy/com/netflix/spinnaker/front50/redis/RedisProjectDAO.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/v2/EntityTagsController.groovy

This is particularly important for EntityTags wherein there can be many
10s of thousands of objects.
The `reindex` API in `clouddriver` will updated such that it passes
`?refresh=false` when retrieving all EntityTags from Front50.
Otherwise this call runs the risk of timing out / failing.

Ability to retrieve most recently cached objects w/o an explicit refresh

---

front50-azure/src/main/java/com/netflix/spinnaker/front50/config/AzureStorageConfig.java

We were getting a bunch of 'Bean' exceptions without this
Related to https://github.com/spinnaker/front50/pull/224

fix(azs): Leverage CommonStorageServiceDAOConfig in AZS

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/config/CommonStorageServiceDAOConfig.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/config/StorageServiceConfigurationProperties.groovy
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/ObjectType.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/pipeline/DefaultPipelineTemplateDAO.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/pipeline/PipelineTemplate.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/pipeline/PipelineTemplateDAO.java
front50-gcs/src/main/java/com/netflix/spinnaker/front50/config/GcsConfig.java
front50-redis/src/main/groovy/com/netflix/spinnaker/front50/redis/RedisConfig.groovy
front50-redis/src/main/groovy/com/netflix/spinnaker/front50/redis/RedisPipelineTemplateDAO.java
front50-web/src/main/groovy/com/netflix/spinnaker/front50/config/Front50WebConfig.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PipelineController.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PipelineTemplateController.java

The whole Redis `findById` iterating and filtering `all()` pattern feels wrong, and the `scope` interaction seems janky, but interested in initial feedback.
@spinnaker/netflix-reviewers PTAL

feat(core): Adding pipeline template storage

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/tag/EntityTags.groovy

This allows a tag to be assigned a category. Alerts/notifications will then be grouped by category in deck.

feat(core/model): Add category to EntityTag model

---

.gitignore
front50-oracle-bmcs/front50-oracle-bmcs.gradle
front50-oracle-bmcs/src/main/java/com/netflix/spinnaker/front50/config/OracleBMCSConfig.java
front50-oracle-bmcs/src/main/java/com/netflix/spinnaker/front50/config/OracleBMCSProperties.java
front50-oracle-bmcs/src/main/java/com/netflix/spinnaker/front50/model/LastModified.java
front50-oracle-bmcs/src/main/java/com/netflix/spinnaker/front50/model/OracleBMCSStorageService.java
front50-web/front50-web.gradle
settings.gradle

Note that we manually download our SDK and add to classpath in our gradle build script. We did this in clouddriver too. This will be fixed once
our SDK is available on Maven central - soon(ish).
Also note that due to the Front50 classpath containing Jersey 1 (brought in by kork IIRC?) we've had to not use our SDK's Jersey 2 based storage
client and instead create a minimal Jersey 1 implementation. Hopefully this can be improved upon in the future either by bumping kork to use
Jersey 2?

feat(oraclebmcs): Add Oracle BMCS Storage Service provider

---

build.gradle
front50-web/src/main/groovy/com/netflix/spinnaker/front50/config/Front50WebConfig.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/NotificationController.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PipelineController.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PipelineTemplateController.java
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/SnapshotsController.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/StrategyController.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/v2/ApplicationsController.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/v2/ProjectsController.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/exceptions/AccessDeniedExceptionHandler.java
front50-web/src/main/groovy/com/netflix/spinnaker/front50/exceptions/DuplicateEntityException.java
front50-web/src/main/groovy/com/netflix/spinnaker/front50/exceptions/InvalidEntityException.java
front50-web/src/main/groovy/com/netflix/spinnaker/front50/exceptions/InvalidRequestException.java
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/PipelineControllerTck.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/SimpleExceptionHandlerExceptionResolver.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/StrategyControllerTck.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/v2/ProjectsControllerTck.groovy

The generic exception handling from `kork-web` allows us to remove nearly
all examples of custom ``@ExceptionHandler` in front50.
Custom handling for `Application.ValidationException` remains and requires
further work in `kork` to fully eliminate.

chore(dependencies): Bump spinnaker-dependencies to 0.101.0

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/pipeline/Pipeline.groovy
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/pipeline/PipelineTemplate.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/pipeline/TemplateConfiguration.java
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PipelineTemplateController.java
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/PipelineTemplateControllerSpec.groovy

@robzienert I was going to put the check for dependent pipeline configs in Orca, but realized that wouldn't work for anyone using Fiat without read access to all applications.

feat(pipeline_template): delete template

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/StorageServiceSupport.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/model/S3StorageService.java

This is a step towards reducing the number of times that `listObjectKeys()`
is called in response to a stale cache being detected.
A loading cache as been added in front `listObjectKeys()`.
As such, loads are restricted to a single thread with all others
blocking and autocompleting after the load completes (provided the last
modified time of the object type remains constant).
This is low hanging fruit that should provide some benefit to anyone
with larger buckets (10k+ pipelines, applications, etc.) and reasonably
high request rates.

perf(core): Debounce concurrent cache refreshes

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/config/CommonStorageServiceDAOConfig.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/DefaultObjectKeyLoader.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/ObjectKeyLoader.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/StorageServiceSupport.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/application/DefaultApplicationDAO.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/application/DefaultApplicationPermissionDAO.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/notification/DefaultNotificationDAO.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/pipeline/DefaultPipelineDAO.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/pipeline/DefaultPipelineStrategyDAO.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/pipeline/DefaultPipelineTemplateDAO.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/project/DefaultProjectDAO.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/serviceaccount/DefaultServiceAccountDAO.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/snapshot/DefaultSnapshotDAO.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/tag/DefaultEntityTagsDAO.java
front50-gcs/src/main/java/com/netflix/spinnaker/front50/config/GcsConfig.java

This will allow cloud providers / implementors to provide alternative
more optimized loads for object metadata (key -> last modified time).
The default implementation is to call `storageService.listObjectKeys()`
directly.

feat(core): Introduce ObjectKeyLoader interface

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/StorageServiceSupport.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3BucketProperties.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3Config.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3Properties.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/model/S3StorageService.java

[Minio s3](https://github.com/minio/minio) compatible storage [isn't supporting versioning](https://github.com/minio/minio/issues/2111) and this causes some issues when using it as storage backend for front50. So, I think it's nice idea to make versioning configurable in configuration file, so if someone is using s3 compatible storage that isn't supporting this, it would be easy to disable it.
As an alternative option, will be autodetection of versioning support on storage, but this might not work well on many different s3 compatible storages.

feat(s3): Allow to disable versioning via config

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PipelineController.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/PipelineControllerTck.groovy

@ajordens PTAL
There's nothing enforcing unique index fields on pipeline configs, which can cause problems when Deck retrieves the configs and finds them missing, as it'll try to correct the issue by adding a unique index and re-saving the pipeline config.
This should still return the pipeline configs in a stable order, with ones that have an explicit index before others, sorting by name and id as fallbacks.

fix(pipelines): sort and apply unique index on application pipelines

---

front50-azure/src/main/java/com/netflix/spinnaker/front50/model/AzureStorageService.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/ObjectKeyLoader.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/StorageService.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/StorageServiceSupport.java
front50-gcs/src/main/java/com/netflix/spinnaker/front50/model/GcsStorageService.java
front50-oracle-bmcs/src/main/java/com/netflix/spinnaker/front50/model/OracleBMCSStorageService.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3Config.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3EventingProperties.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3Properties.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/model/EventingS3ObjectKeyLoader.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/model/S3StorageService.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/model/TemporarySQSQueue.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/model/events/S3Event.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/model/events/S3EventWrapper.java
front50-s3/src/test/groovy/com/netflix/spinnaker/front50/model/EventingS3ObjectKeyLoaderSpec.groovy
front50-s3/src/test/groovy/com/netflix/spinnaker/front50/model/TemporarySQSQueueSpec.groovy
front50-swift/src/main/java/com/netflix/spinnaker/front50/model/SwiftStorageService.java

Adds a new `ObjectKeyLoader` implementation that subscribes to an sqs
queue and receives events generated in response to s3 modifications.
These events should be received no more than 1s after the modification.
This PR also removes the unused `loadObjectsWithPrefix` StorageService
method.

feat(aws): Support for incremental cache updates based on s3 events

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/config/CommonStorageServiceDAOConfig.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/config/StorageServiceConfigurationProperties.groovy
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/ObjectType.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/intent/DefaultIntentDAO.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/intent/Intent.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/intent/IntentDAO.java
front50-redis/src/main/groovy/com/netflix/spinnaker/front50/redis/RedisConfig.groovy
front50-redis/src/main/groovy/com/netflix/spinnaker/front50/redis/RedisIntentDAO.java
front50-web/src/main/groovy/com/netflix/spinnaker/front50/config/Front50WebConfig.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/IntentController.java
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/IntentControllerSpec.groovy

Basics of intent storage for keel. Object looks like https://github.com/spinnaker/keel/blob/master/README.md.
@ajordens @robzienert PTAL

feat(keel): adding basic storage of intents

---

front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3Config.java

This leads to an exception when using s3 compatible systems like minio. Error creating bean with name 'awsSQSClient' defined in class path resource [com/netflix/spinnaker/front50/config/S3Config.class]

fix(s3): don't create sqs and sns topics when eventing is disabled

---

front50-web/etc/init/front50.conf

Changing to appending to the log file so logs will correctly rotate.  This prevents large amounts of null data at the start of a rotated log file.

fix(front50/log): Append to log instead of overwrite

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PipelineTemplateController.java
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/PipelineTemplateControllerSpec.groovy

For template type and source prefix used shared strins.

refactor(pipelineTemplates): Use shared strings

---

front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3Config.java

Checks for an non empty string before using it as an endpoint for the S3.  This comes up in cases when a user leaves optionally leaves the field empty in a properties file if the env var doesn't exist.  For example, the following configuration would result in an empty string if `services.front50.endpoint` doesn't exist.
```
spinnaker:
s3:
enabled: true
bucket: ${services.front50.storage_bucket:}
rootFolder: ${services.front50.rootFolder:front50}
endpoint: ${services.front50.endpoint:}
```

refactor(S3): checks for non empty string before using it as an endpoint

---

front50-oracle-bmcs/src/main/java/com/netflix/spinnaker/front50/model/OracleBMCSStorageService.java

Fixes the spinnaker/spinnaker#2648 bug where the user sees "Could not create application: Cannot get property 'name' on null object".
Tested locally running deck, redis, gate, orca, front50 - you can now successfully create applications with front50 backed by oracelbmcs storage service.

fix(oraclebmcs): Throw NotFoundException instead of return null

---

front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3BucketProperties.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3Config.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3Properties.java

some s3 compatible storage solutions (minio, for example) take the region into account when validating incoming requests but allow you to set non-aws region identifiers. this change allows you to explicitly set the region identifier as an override via `regionOverride`. it also allows you to set the region for configurations using the `endpoint` setting.

feat(s3): add regionOverride property

---

front50-core/front50-core.gradle
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/StorageServiceSupport.java

Correctly propagate the authenticated username across thread boundaries
in `bulkImport`.

fix(core): Fix auth propagation for `bulkImport` calls

---

front50-s3/src/main/java/com/netflix/spinnaker/front50/model/S3StorageService.java

In such cases, it is more efficient to just `loadObject(type, key)`.

perf(s3): Short circuit when asking for object history w/ maxResults = 1

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/ItemDAO.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/StorageService.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/StorageServiceSupport.java
front50-migrations/src/main/java/com/netflix/spinnaker/front50/migrations/EnsureCronTriggerHasIdentifierMigration.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/model/S3StorageService.java
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/v2/EntityTagsController.groovy

Ultimately delegates to the `deleteObjects` available for S3, other
providers will continue to use their respective per-object delete
functions.
```
curl -X "POST" "https://localhost:8081/v2/tags/batchDelete" \
-H 'Content-Type: application/json' \
-d $'[
"aws:servergroup:app-v023:111111111111:us-west-2",
"aws:servergroup:app-v000:111111111111:us-east-1"
]'
'
```

feat(entitytags): Support for bulk delete of entity tags

---

README.md
build.gradle

Starting front50 with ./gradlew -DDEBUG=true now causes the JVM to listen on port 8180 for a remote debugger.

chore(build): Add debug flag to front50 build

---

front50-gcs/src/main/java/com/netflix/spinnaker/front50/config/GcsConfig.java

The GCS ApplicationPermissionDAO is using the modification time of
'specification.json' to determine cache expiration but is actually
reading 'permission.json', leading to incorrect caching.
Cherry pick of #326

fix(google): Fix caching of permissions (#326)

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/ServiceAccountsController.groovy

We should be sending a list of service account roles for Fiat to refresh, not the serviceAccount names.
See https://github.com/spinnaker/fiat/blob/master/fiat-web/src/main/java/com/netflix/spinnaker/fiat/controllers/RolesController.java#L99
@stewchen @danielpeach

fix(service-accounts): Fiat role sync requires a list of roles not users

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PipelineController.groovy

This allows the `SavePipelineTask` in `orca` to correctly capture the
pipeline identifier.

fix(web): savePipeline() should return the newly created pipeline

---

front50-gcs/src/main/java/com/netflix/spinnaker/front50/model/GcsStorageService.java

Currently if we fail to update the lastmodified file in storage, due to a 429 (Too Many Requests) response, we queue a request to re-try in 1s. While that request is queued, we should short-circuit any
other attempts to update lastmodified.

fix(google): Block updates to lastmodified when update is queued

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/StorageServiceSupport.java
front50-gcs/src/main/java/com/netflix/spinnaker/front50/model/GcsStorageService.java

If there are objects in the bucket that front50 is polling that weren't added by front50, some buggy behavior can occur:
* Specific to GCS, objects that match `(.*)[^/]specification.json` are returned by the listing operation, but the actual fetch operation looks for `$1/specification.json` causing a 404.
* For all back-ends, objects whose key does not match do not match their id are cached every cycle.  (Aside from this caching every cycle, looking up the objects by id does not work because the lookup logic assumes the key matches the id.)
The above situations should not occur for any object created by Spinnaker, but let's make the logic robust and/or warn if there are unexpected objects in the bucket.

 fix(core): Warn when an object's key does not match its id

---

front50-oracle/front50-oracle.gradle

Upgrade the Oracle OCI SDK dependency in front50-oracle to 1.2.44.  The similar change had been done in clouddriver which uses the same Oracle OCI SDK dependency.  https://github.com/spinnaker/clouddriver/blob/master/clouddriver-oracle/clouddriver-oracle.gradle

chore(oracle/dependency): upgrade oracle oci sdk version to 1.2.44

---

build.gradle
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3Config.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3Properties.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/model/S3StorageService.java

Some S3 compatible stores don't support 10000 objects retrieved per object. This PR adds a spinnaker.s3.maxKeys setting to let user override the S3 listObject request. It defaults to 10000 as currently.

fix(s3): Add control over nb of objects retrieved per batch (maxKeys)

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/config/GraphQLSchemaConfiguration.java

Fetching the schema resource is failing when it's in a jar file as it can't be read as a File. Switch to getting the schema as an InputStream.

fix(web): Fix startup failure due to graphql

---

README.md

Remove cassandra from the Readme as it isn't a supported provider anymore.

docs(*): Remove Cassandra from Readme

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/v2/ApplicationsController.groovy

Supports serving all applications out of a gate cache (with auth applied
as a post filter).

fix(web): Support unrestricted fetching of `/applications`

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/pipeline/Pipeline.groovy
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/pipeline/Trigger.java
front50-web/src/main/groovy/com/netflix/spinnaker/front50/config/GraphQLSchemaConfiguration.java
front50-web/src/main/groovy/com/netflix/spinnaker/front50/graphql/datafetcher/DataFetchingEnvironmentPredicate.java
front50-web/src/main/groovy/com/netflix/spinnaker/front50/graphql/datafetcher/PipelinesDataFetcher.java
front50-web/src/main/groovy/com/netflix/spinnaker/front50/graphql/datafetcher/TriggersDataFetcher.java
front50-web/src/main/resources/graphql/pipelineConfig.graphqls
front50-web/src/test/groovy/com/netflix/spinnaker/front50/graphql/datafetcher/DisabledPredicateSpec.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/graphql/datafetcher/HavingTriggerTypePredicateSpec.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/graphql/datafetcher/TriggersDataFetcherSpec.groovy

Here's some more stuffs for our POC. Starting to find my feet from a server perspective; the client side of things is still quite dodgy.
```graphql
query {
pipelines(havingTriggerType: "cron", disabled: false) {
id
name
application
triggers(types: ["cron"]) {
... on CronTrigger {
id
enabled
cronExpression
}
}
}
}
```

feat(graphql): Additional trigger filtering

---

front50-web/front50-web.gradle

Becasue the oci-sdk jars are not published in maven (https://github.com/oracle/oci-java-sdk/issues/25), the dependency are 'dynamically' declared during fetching and unpacking the oci-sdk. If ':front50-web:startScripts' runs before ':front50-oracle:unpackSdk' finished, the oci-sdk jars then could be missing in the generated script. The fix adds dependsOn and mustRunAfter ':front50-oracle:unpackSdk' to front50-web:startScripts

fix(provider/oracle): fix missing oci-sdk jars in web startScript

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/ServiceAccountsController.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/ServiceAccountsControllerSpec.groovy

We use managed service accounts and immediately after we create them, we need to save the pipeline that uses it. This causes that sometimes the Fiat cache is not fresh enough to know about the new service account and we get 404 in Orca while creating the pipelines with the new roles.
We found that using `loginWithRoles` instead of `sync`, makes Fiat aware of the new service account.

fix(serviceAccounts): Sync new service accounts with Fiat explicitly

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PermissionsController.groovy

This endpoint is a building block for making it possible to push new
applications into the fiat application cache when they are created.
Currently FIAT updates its application cache every 20th second and this
will help us being able to trigger updates to the cache when an
application is created.
It will follow a PR to fiat that leverages this endpoint. When both of
these are merged there will come a new front50 PR that triggers the fiat
endpoint for adding a new app so that applications will be available to
users immediately after an application is created

feat(app/permission): endpoint for single app permissions

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/application/Application.groovy

Turns out Front50 serializes null values, surprise

fix(trafficguards): default to empty list of traffic guards

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/application/Application.groovy
front50-core/src/test/groovy/com/netflix/spinnaker/front50/model/application/ApplicationModelSpec.groovy

https://github.com/spinnaker/orca/pull/2604 assumes `cloudProviders` is a string, so let's make sure it is

refactor(application): ensure cloudProviders is a comma-separated string

---

front50-migrations/src/main/java/com/netflix/spinnaker/front50/migrations/CloudProvidersStringMigration.java
front50-migrations/src/test/groovy/com/netflix/spinnaker/front50/migrations/CloudProvidersStringMigrationSpec.groovy

Cleans up data to ensure `cloudProviders` is a string

refactor(applications): migrate cloudProviders to comma-separated string

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/application/Application.groovy
front50-core/src/test/groovy/com/netflix/spinnaker/front50/model/application/ApplicationModelSpec.groovy

The cloudProviders field on applications is not being persisted; it was promoted from 'details' to its own field, but 'getPersistedProperties' was not updated so it is not being set when initializing a new application from the JSON that is posted to front50.  Update getPersistedProperties so it is properly persisted and add a test case.
Fixes a bug from #427 which was caught by our integration tests.

fix(application): Fix persistence of cloudProviders

---

front50-gcs/front50-gcs.gradle
front50-gcs/src/main/java/com/netflix/spinnaker/front50/model/GcsStorageService.java

front50-gcs currently depends on all google libraries whereas it only needs to depend on googleStorage; remove the extra dependencies.  Also, add in explicit dependencies that were transitively included.

chore(google): Clean up front50-gcs dependencies

---

front50-redis/src/test/groovy/com/netflix/spinnaker/front50/redis/RedisApplicationDAOSpec.groovy

Broke in https://github.com/spinnaker/front50/pull/427
FYI @ezimanyi

fix(test/redis): cloudProviders is promoted to its own field now

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/application/Application.groovy

Defaulting this to an empty list also means we will always have an empty list when performing an update, which is not great.

fix(core): do not overwrite traffic guard configurations

---

front50-redis/src/test/groovy/com/netflix/spinnaker/front50/redis/RedisApplicationDAOSpec.groovy

Locally front50 tests were failing due to a missing traffic guard object in the created application. This fixes the tests, can you verify that this is correct?

fix(application): fix tests

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/application/Application.groovy

The last commit incorrectly resolved a merge conflict; cloudProviders was never in the 1.12 branch and should not have been added.  Instead, trafficGuards should have been removed.

fix(core): Fix merge conflict on cherry-pick

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/pipeline/Pipeline.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/ReorderPipelinesController.java

Adds `/reorder` endpoint for pipelines and pipeline strategies, so that these resources can be re-indexed with one request from Deck rather than one request per pipeline.
Corresponding PRs:
Deck: [spinnaker/deck#6519](https://github.com/spinnaker/deck/pull/6519)
Gate: [spinnaker/gate#723](https://github.com/spinnaker/gate/pull/723)
Orca: https://github.com/spinnaker/orca/pull/2663

feat(core): add endpoint for reordering pipelines

---

front50-migrations/src/main/java/com/netflix/spinnaker/front50/migrations/RemoveApplicationAccountsMigration.java

Long ago, we forced our users to select a set of accounts when creating an application. Later, in the UI, we stopped letting people edit the field, but we still show it in a few places (search, application list, application attributes) and that's confusing.

refactor(applications): remove accounts field from application metadata

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/application/Application.groovy
front50-migrations/src/main/java/com/netflix/spinnaker/front50/migrations/CloudProvidersStringMigration.java
front50-migrations/src/main/java/com/netflix/spinnaker/front50/migrations/RemoveApplicationAccountsMigration.java

The `Application` class is weird and doesn't have the `dao` set on it, even though it relies on it for updates (turns out it gets added in the controller). So our migrations are quickly and quietly failing on the first attempted update.

fix(applications): add dao to application before updating

---

front50-redis/src/test/groovy/com/netflix/spinnaker/front50/redis/config/EmbeddedRedisConfig.java

The refactor of the tests added a redis leak; destroy the bean when it goes out of scope so we don't have a redis outlive the test.

fix(redis): Fix embedded redis leak

---

front50-migrations/src/main/java/com/netflix/spinnaker/front50/migrations/RunAsUserToPermissionsMigration.java
front50-migrations/src/test/groovy/com/netflix/spinnaker/front50/migrations/RunAsUserToPermissionsMigrationSpec.groovy

This migration will migrate pipelines that have manual service users to use the new permissions format. It will only run on pipelines where `roles` are not present and `runAsUser` is set to a non-managed service account.
The migration job will automatically create the new managed service users, and the new service user will get the same permissions as the manual service user that it replaces.
The migration must be manually enabled by setting the property `migrations.migrateToManagedServiceAccounts` to `true`.
*Note:* If a pipeline has multiple triggers with _different_ `runAsUser`'s set, the new managed service user will get all of the roles of the different manual service users (as you can only have one managed service user per pipeline). This can potentially remove some users ability to …

feat(authz): Migrate manual service users to managed service users

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PipelineController.groovy

Needed because we sometimes generate the pipeline id outside Front50 (e.g. https://github.com/spinnaker/orca/pull/2754)

fix(pipelines): More robust handling of missing cron trigger id's

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/ServiceAccountsController.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/ServiceAccountsControllerSpec.groovy

Doing a full sync implies querying all the service accounts back to
front50 when doing the sync. However, we only need to pass the roles of
the service user being created. This helps on sync time when the amount
of service accounts is huge.

chore(syncroles): Sync only the service account roles

---

front50-migrations/src/main/java/com/netflix/spinnaker/front50/migrations/RunAsUserToPermissionsMigration.java
front50-migrations/src/test/groovy/com/netflix/spinnaker/front50/migrations/RunAsUserToPermissionsMigrationSpec.groovy

If a pipeline has two or more triggers, but not all are updated to automatic service accounts, the pipeline would still be skipped in the migration because `roles` would already be present. This PR fixes so that existing roles will be handled and triggers with manual service users are always migrated.

fix(authz): Automatic Service Account migration missing some pipelines

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/pipeline/PipelineTemplate.java
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/V2PipelineTemplateController.java

Also: 
* made some fixes to digest last updated time handling -- previously on each update we were calculating a different hash due to the update time rolling.
* fixed strange error handling in `/create` where we would no-op and succeed when trying to write a duplicate id + tag combo.

feat(MPTv2): Updates latest tag on v2 MPT write.

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/v2/ApplicationsController.groovy

In the cases where the application metadata has the permissions block
(for whatever reason - it should never have it) but the actual permissions are
empty, querying the application (via `/v2/applications/{appname}`) will return
the erroneous permissions object. Instead, make the single app getter EP
symmetric with all application getter EP (`/v2/applications`) and strip out
the permissions object when the permissions aren't there
see https://github.com/spinnaker/front50/pull/505 for change to the all
applications endpoint

fix(permissions): Make permission retrieval consistent

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/AuthorizationSupport.groovy

A Fiat service account should have EXECUTE on an application in order to access it. This check happens before the pipeline is saved. 
Backwards compatibility for applications missing EXECUTE permissions is maintained via https://github.com/spinnaker/fiat/pull/390
Part of spinnaker/spinnaker#3554

feat(authz): Check service acct has EXECUTE permission on application.

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/StorageServiceSupport.java
front50-gcs/src/main/java/com/netflix/spinnaker/front50/model/GcsStorageService.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/model/S3StorageService.java

Currently we're relying on the underlying `StorageService` implementations
to set and track lastModified and lastModifiedBy.
Pulling it up to the `StorageServiceSupport` ensures consistent behavior
across all current and future `StorageService` implementations.

fix(core): Ensure lastModified and lastModifiedBy is set on item

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/StorageService.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/StorageServiceSupport.java

This PR allows a `StorageService` implementation to support bulk
loading of objects.
Default implementation raises an `UnsupportedOperationException` and
triggers the legacy rxJava-backed loads.

feat(core): Support for `loadObjects`

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/StorageServiceSupport.java

Previously was using `Timestamped::getId` which may not always return
_expected_ lower case `id`.

fix(core): A better case insensitive comparison when bulk loading objects

---

build.gradle
front50-bom/front50-bom.gradle

compileOnly dependency should not be added to generated pom.xml,
see discussion: https://discuss.gradle.org/t/publishing-plugin-should-respect-compileonly-configuration/22903/2
see related commit: nebula-plugins/nebula-publishing-plugin@a5432aa

fix(bom): Fix generated pom.xml to omit invalid lombok declaration

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/AdminOperations.java
front50-sql/src/main/kotlin/com/netflix/spinnaker/front50/model/SqlStorageService.kt
front50-sql/src/test/kotlin/com/netflix/spinnaker/front50/model/SqlStorageServiceTests.kt
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/AdminController.java

This endpoint supports the recovery of arbitrary objects that have
previously been deleted.
Currently supports `SQL` but any versioned storage service can implement
the `AdminOperations` interface.

feat(web): New `/admin/recover` endpoint

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/exceptions/AccessDeniedExceptionHandler.java

Log out the source exception which resulted in an access denied response.
Otherwise, it's really hard to debug what caused the access denied

fix(exception handlers): log out exception for access denied

---

front50-sql-mysql/front50-sql-mysql.gradle
front50-sql/front50-sql.gradle

This change allows a custom build of Spinnaker to exclude the `mysql-connector-java` driver from the generated distribution with a build command like:
`./gradlew front50-web:installDist -x test -PexcludeSqlDrivers`
The driver is included in the build by default, so the build results are not changed for existing open-source and custom builds. 
The Gradle dependency types were changed from `implementation` to `runtimeOnly` to reflect the fact that `mysql-connector-java` is not needed for compilation.

feat(sql): Conditionally allow MySQL Connector to be excluded from the build

---

gradle.properties

Upgrading the fiat library version to >= 1.6.0 fills the front50 logs with this error:
groovy.lang.MissingMethodException: No signature of method: com.netflix.spinnaker.fiat.model.resources.Permissions.isEmpty() is applicable for argument types: () values: []
This is because that method was removed in spinnaker/fiat#481 (which went into fiat 1.6.0). It's called from front50 in `ApplicationsController#78`.

fix(fiat): roll back fiat to 1.5.1

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/v2/ApplicationsController.groovy

Having added `canCreate` to fiat, we can now use it here to restrict application creation

feat(authorization): Add create restriction to application creation

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PipelineController.groovy

There's currently no endpoint in front50 to get the current pipeline definition; consumers need to call the history endpoint with a limit of 1 and take the single returned element.
Let's make the API simpler for consumers who just want the current definition by giving them an endpoint to return it.
Forcing consumers to call the /history endpoint has led to performance issues, as that endpoint is often much slower than a call to get the current definition. Some backing stores have optimized to short-circuit the limit=1 case (s3 in #316), but others (including GCS) are still very slow even in the limit=1 case.
We could (and potentially should) make the same optimization to other backing stores. But I think the fundamental issue here is that we have rare, slow history-type requests and …

feat(core): Add endpoint to get current pipeline definition

---

front50-core/front50-core.gradle
front50-core/src/main/groovy/com/netflix/spinnaker/front50/ApplicationPermissionsService.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/config/ChaosMonkeyEventListenerConfigurationProperties.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/config/FiatConfigurationProperties.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/config/Front50CoreConfiguration.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/events/ApplicationPermissionEventListener.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/listeners/ChaosMonkeyEventListener.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/application/Application.groovy
front50-core/src/test/groovy/com/netflix/spinnaker/front50/ApplicationPermissionsServiceSpec.groovy
front50-core/src/test/groovy/com/netflix/spinnaker/front50/listeners/ChaosMonkeyEventListenerSpec.groovy
front50-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlConfiguration.kt
front50-sql/src/main/kotlin/com/netflix/spinnaker/front50/migrations/StorageServiceMigrator.kt
front50-sql/src/main/kotlin/com/netflix/spinnaker/front50/model/SqlStorageService.kt
front50-sql/src/test/kotlin/com/netflix/spinnaker/front50/model/SqlStorageServiceTests.kt
front50-sql/src/test/kotlin/com/netflix/spinnaker/front50/model/TestDatabase.kt
front50-web/src/main/groovy/com/netflix/spinnaker/front50/Main.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/config/Front50WebConfig.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PermissionsController.groovy
gradle.properties

Enforces that Chaos Monkey has the permissions it needs to terminate instances within an application if enabled. This introduces a new config: `spinnaker.chaos-monkey.user-role`, which should be the principal user that Chaos Monkey works as (e.g. `chaos-monkey@example.com`. Updates to either application settings or application permissions will trigger this event listener.
While working on this, I also moved business logic out of the controller layer and into a service.
The PR is broken into two commits, the first is just moving logic for permissions into `ApplicationPermissionsService`, the second is for adding the chaos monkey functionality.

feat(chaosmonkey): Enforce chaos monkey permissions when enabled

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/V2PipelineTemplateController.java

https://github.com/spinnaker/spinnaker/issues/4670
This updates the list pipeline templates endpoint to return a map of pipeline templates grouped and sorted by their ids. It also adds filtering to only return v2 templates. This supports displaying versioning in the UI and Spin.
Related PRs:
[Gate](https://github.com/spinnaker/gate/pull/989)
[Deck](https://github.com/spinnaker/deck/pull/7708)
[Spin](https://github.com/spinnaker/spin/pull/235)

feat(core): Filter by v2 and group template versions

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/config/CommonStorageServiceDAOConfig.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/config/StorageServiceConfigurationProperties.groovy
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/ObjectType.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/pluginartifact/DefaultPluginArtifactRepository.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/pluginartifact/PluginArtifact.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/pluginartifact/PluginArtifactRepository.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/pluginartifact/PluginArtifactService.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/validator/HasCanonicalPluginIdValidator.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/validator/HasValidRequiresFieldsValidator.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/validator/PluginArtifactValidator.java
front50-core/src/test/groovy/com/netflix/spinnaker/front50/model/pluginartifact/PluginArtifactServiceSpec.groovy
front50-core/src/test/groovy/com/netflix/spinnaker/front50/model/pluginartifact/PluginArtifactSpec.groovy
front50-core/src/test/groovy/com/netflix/spinnaker/front50/validator/HasCanonicalPluginIdValidatorSpec.groovy
front50-core/src/test/groovy/com/netflix/spinnaker/front50/validator/HasValidRequiresFieldsValidatorSpec.groovy
front50-sql/src/main/kotlin/com/netflix/spinnaker/front50/model/SqlStorageService.kt
front50-sql/src/main/resources/db/changelog-master.yml
front50-sql/src/main/resources/db/changelog/20191213-initial-plugin-artifacts-schema.yml
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PluginArtifactController.java

This is an optional feature for plugins. This makes front50 the source of
truth of what plugins are available for download by any particular service.
Which plugin release is actually downloaded for a particular service is
determined by the service itself.
⚠️ Going to hold off on merge until I write up the `Front50UpdateRepository` in `kork-plugins`, just getting all of the pieces in place.
Before this is merged, there's question about how much context we put into the repository on initial roll out. Right now I have things written such that plugin releases define what services they support, but nothing much beyond that. Should plugin releases also define service version constraints? I think yes, but I'm unsure how much we need to bite off out of the gate.
This PR just provides services of …

feat(plugins): Adds plugin artifact repository

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/pluginartifact/PluginArtifactService.java
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PluginArtifactController.java

Reverts spinnaker/front50#670
This is causing a startup issue in my local instance:
```
Caused by: java.lang.IllegalStateException: Ambiguous mapping. Cannot map 'pluginArtifactController' method 
java.util.Collection<com.netflix.spinnaker.front50.model.pluginartifact.PluginArtifact> com.netflix.spinnaker.front50.controllers.PluginArtifactController.list(java.lang.String)
to {GET /pluginArtifacts}: There is already 'pluginArtifactController' bean method
com.netflix.spinnaker.front50.model.pluginartifact.PluginArtifact com.netflix.spinnaker.front50.controllers.PluginArtifactController.get(java.lang.String) mapped.
```

Revert "fix(plugins): Add GET by pluginId"

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/listeners/ChaosMonkeyEventListener.java
front50-core/src/test/groovy/com/netflix/spinnaker/front50/listeners/ChaosMonkeyEventListenerSpec.groovy

The previous implementation was flawed for a few reasons.
1) ApplicationDAO does not persist permissions, so the implementation of `ApplicationEventListener` did nothing.
2) When a user updates Chaos Monkey permissions from Deck, permissions are not passed to the Orca task `UpsertApplicationTask`, which means that the chaos monkey `ApplicationPermissionEventListener` implementation would not be triggered.
3) When the chaos monkey `ApplicationPermissionEventListener` was triggered (via an Application permissions update event, like saving perms through Deck), a check to see if the permissions were unrestricted did not exist.  This would lock people out of READ and WRITE permissions since only the chaos monkey permission would be applied.
This fix addresses these issues.  I've removed the …

fix(permissions): Update and persist chaos monkey permissions on application PRE_UPDATE event

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/ApplicationPermissionsService.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/listeners/ChaosMonkeyEventListener.java
front50-core/src/test/groovy/com/netflix/spinnaker/front50/listeners/ChaosMonkeyEventListenerSpec.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PermissionsController.groovy

Once we remove chaos monkey permissions sent via Deck, this will allow us to persist chaos monkey permissions when Deck submits a permissions map (either empty or with permissions).

fix(permissions): Apply chaos monkey permissions on application update permissions event

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/ApplicationPermissionsService.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/listeners/ChaosMonkeyApplicationEventListener.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/listeners/ChaosMonkeyApplicationPermissionEventListener.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/listeners/ChaosMonkeyEventListener.java
front50-core/src/test/groovy/com/netflix/spinnaker/front50/listeners/ChaosMonkeyApplicationEventListenerSpec.groovy
front50-core/src/test/groovy/com/netflix/spinnaker/front50/listeners/ChaosMonkeyApplicationPermissionEventListenerSpec.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PermissionsController.groovy

https://github.com/spinnaker/front50/pull/673 intoruduced a circular dependency between `ChaosMonkeyEventListener` and `ApplicationPermissionsService` which this resolves.  
Otherwise, it's the same basic change which resolves this issue:
Once we remove chaos monkey permissions sent via Deck, this will allow us to persist chaos monkey permissions when Deck submits a permissions map (either empty or with permissions).

fix(permissions): Add abstract class ChaosMonkeyEventListener and chaos monkey ApplicationPermissionEventListener implementation

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/listeners/ChaosMonkeyApplicationEventListener.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/listeners/ChaosMonkeyApplicationPermissionEventListener.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/listeners/ChaosMonkeyEventListener.java
front50-core/src/test/groovy/com/netflix/spinnaker/front50/listeners/ChaosMonkeyApplicationEventListenerSpec.groovy
front50-core/src/test/groovy/com/netflix/spinnaker/front50/listeners/ChaosMonkeyApplicationPermissionEventListenerSpec.groovy

In my glee to make sure we never ended up in a situation that locked people out, I got a bit carried away with removing permissions.  I really hope this is the final solution here.  Also includes a small code cleanup.

fix(permissions): Only remove chaos monkey if it is the only permission, plus small code cleanup

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/pluginartifact/PluginArtifactService.java
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PluginArtifactController.java

This will support the writing of the `Front50UpdateRepository` in `kork`, which is caputred in https://github.com/spinnaker/spinnaker/issues/5241
Specifically, this will satisfy pf4j's `UpdateRepository`:
https://github.com/pf4j/pf4j-update/blob/master/src/main/java/org/pf4j/update/UpdateRepository.java#L49

feat(plugins): Add get by ID endpoint to PluginArtifactController

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/config/CommonStorageServiceDAOConfig.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/config/StorageServiceConfigurationProperties.groovy
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/ObjectType.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/plugininfo/DefaultPluginInfoRepository.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/plugininfo/PluginInfo.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/plugininfo/PluginInfoRepository.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/plugininfo/PluginInfoService.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/validator/HasCanonicalPluginIdValidator.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/validator/HasValidRequiresFieldsValidator.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/validator/PluginInfoValidator.java
front50-core/src/test/groovy/com/netflix/spinnaker/front50/model/plugininfo/PluginInfoServiceSpec.groovy
front50-core/src/test/groovy/com/netflix/spinnaker/front50/model/plugininfo/PluginInfoSpec.groovy
front50-core/src/test/groovy/com/netflix/spinnaker/front50/validator/HasCanonicalPluginIdValidatorSpec.groovy
front50-core/src/test/groovy/com/netflix/spinnaker/front50/validator/HasValidRequiresFieldsValidatorSpec.groovy
front50-sql/src/main/kotlin/com/netflix/spinnaker/front50/model/SqlStorageService.kt
front50-sql/src/main/resources/db/changelog-master.yml
front50-sql/src/main/resources/db/changelog/20200113-rename-plugin-artifacts-to-plugin-info.yml
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PluginInfoController.java

We decided this rename makes sense for the following reasons:
- It follows existing pf4j terminology (https://github.com/pf4j/pf4j-update/blob/master/src/main/java/org/pf4j/update/PluginInfo.java)
- It more accurately describes this resource - the resource being plugin artifact information vs. the actual plugin artifact (which will be stored elsewhere).

refactor(plugins): Rename from PluginArtifact to PluginInfo

---

front50-sql/front50-sql.gradle
front50-sql/src/main/kotlin/com/netflix/spinnaker/config/CompositeStorageServiceConfiguration.kt
front50-sql/src/main/kotlin/com/netflix/spinnaker/front50/migrations/StorageServiceMigrator.kt
front50-sql/src/test/kotlin/com/netflix/spinnaker/config/CompositeStorageServiceConfigurationTests.kt
front50-web/src/main/groovy/com/netflix/spinnaker/front50/config/Front50WebConfig.groovy
gradle.properties

Turns out to be more boilerplate than I like, but at the end of the day I just want a bean that lets me access the request context instead of directly grabbing values in and out of the MDC

fix(kork): use a context object instead of raw MDC access

---

front50-s3/front50-s3.gradle

We are running Spinnaker on EKS and would like to grant the front50 pods permissions to S3 through the EKS pod identity webhook. Currently this fails with
```
Unable to load AWS credentials from any provider in the chain: 
[...]
WebIdentityTokenCredentialsProvider: To use assume role profiles the aws-java-sdk-sts module must be on the class path., 
[...]
Internal Server Error
```
Therefore I would like to include the `aws-java-sdk-sts`.

feat(s3): Add aws-java-sdk-sts to support roles provided by EKS pod identity webhook

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/config/PluginBinaryCacheConfiguration.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/plugininfo/PluginInfo.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/plugininfo/PluginInfoRepository.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/plugins/CachingPluginBinaryStorageService.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/plugins/PluginBinaryAlreadyExistsException.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/plugins/PluginBinaryStorageService.java
front50-core/src/test/groovy/com/netflix/spinnaker/front50/plugins/CachingPluginBinaryStorageServiceSpec.groovy
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3Config.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3EventingConfiguration.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3PluginBinaryServiceConfiguration.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3StorageServiceConfiguration.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/plugins/S3PluginBinaryStorageService.java
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PluginBinaryController.java

Refactors `front50-s3` config so that the StorageService can decoupled from S3 configuration. Added a new storage service just for plugin binaries that can use different (already available) blob stores. Only wrote an S3 implementation for now since that's all Netflix cares about.
Also wrote a little local filesystem cache that delegates to actual storage services.
Additional steps:
1. Get the gradle plugin to work with these endpoints
2. Get the plugin framework to download from front50
For Front50 plugin bootstrapping itself, its plugins will need to be baked into the image, or sourced from an already existing Front50 deployment.

feat(plugins): Plugin binary store service

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/plugins/CachingPluginBinaryStorageService.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3ClientFactory.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3Config.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3EventingConfiguration.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3MetadataStorageProperties.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3PluginStorageConfiguration.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3PluginStorageProperties.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3Properties.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3StorageServiceConfiguration.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/model/EventingS3ObjectKeyLoader.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/plugins/S3PluginBinaryStorageService.java
front50-s3/src/test/groovy/com/netflix/spinnaker/front50/model/EventingS3ObjectKeyLoaderSpec.groovy

I forgot that we need to support configuring plugin binaries to go to a different bucket. The normal S3 bucket is typically versioned, whereas the plugin binaries bucket should not be. This refactor keeps all existing S3 configuration the same, but adds all new config for the plugin storage.

fix(s3): Refactor S3 config to support separate plugin binaries bucket

---

front50-swift/front50-swift.gradle

Upgrade openstack4j version.
Fix CVE-2016-9606 and CVE-2016-6346 caused by resteasy-jaxrs.

chore(vulnerabilities): resolve CVEs and other security issues

---

gradle/kotlin.gradle

Bumping kork on front50 is failing because at some point recently we upgraded kotlin, and it looks like it has a new artifact that isn't in the pinned version.
I'm not sure why the pin was added initially, but the tests all pass when it is removed. When this is removed, kork can successfully be bumped.

chore(dependencies): Unpin org.jetbrains.kotlin

---

halconfig/README.md
halconfig/front50.yml

* refactor(core): add README to halconfig directory 
* refactor(core): remove cassandra config from halconfig/front50.yml 
Cassandra was [removed](https://github.com/spinnaker/front50/pull/353) as a storage provider in 2018, so we should no longer need this config block disabling it.

refactor(core): clean up halconfig/front50.yml

---

front50-azure/src/main/java/com/netflix/spinnaker/front50/config/AzureStorageProperties.java

This defaulting was happening in Halyard, and will be removed from kleat (which does not default parameters that are not supplied and instead leaves this defaulting to the consuming service).
In order to support kleat, add the defaulting here; this won't affect existing Halyard users as Halyard will continue to write this field (meaning the deafult won't be used for them).

chore(azure): Default storageContainerName

---

front50-core/front50-core.gradle
front50-core/src/main/groovy/com/netflix/spinnaker/front50/config/CommonStorageServiceDAOConfig.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/config/Front50CoreConfiguration.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/config/PluginVersionCleanupProperties.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/config/PluginVersioningConfiguration.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/ObjectType.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/plugins/DefaultPluginInfoRepository.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/plugins/DefaultPluginVersionPinningRepository.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/plugins/PluginInfo.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/plugins/PluginInfoRepository.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/plugins/PluginInfoService.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/plugins/PluginVersionCleanupAgent.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/plugins/PluginVersionPinningRepository.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/plugins/PluginVersionPinningService.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/plugins/ServerGroupPluginVersions.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/validator/HasCanonicalPluginIdValidator.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/validator/HasValidRequiresFieldsValidator.java
front50-core/src/test/groovy/com/netflix/spinnaker/front50/model/plugins/PluginInfoServiceSpec.groovy
front50-core/src/test/groovy/com/netflix/spinnaker/front50/model/plugins/PluginInfoSpec.groovy
front50-core/src/test/groovy/com/netflix/spinnaker/front50/model/plugins/PluginVersionCleanupAgentSpec.groovy
front50-core/src/test/groovy/com/netflix/spinnaker/front50/model/plugins/PluginVersionPinningServiceSpec.groovy
front50-core/src/test/groovy/com/netflix/spinnaker/front50/validator/HasCanonicalPluginIdValidatorSpec.groovy
front50-core/src/test/groovy/com/netflix/spinnaker/front50/validator/HasValidRequiresFieldsValidatorSpec.groovy
front50-sql/src/main/kotlin/com/netflix/spinnaker/front50/model/SqlStorageService.kt
front50-sql/src/main/resources/db/changelog-master.yml
front50-sql/src/main/resources/db/changelog/20200428-initial-plugin-versions-schema.yml
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PluginInfoController.java
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PluginVersionController.java

Adds new metadata store for pinning plugin versions to a server group. This
ensures a server group will continue to load the same plugins even through
instance replacement on long-lived server groups.
Metadata is regularly cleaned up, leaving the last N records for a particular
cluster, by default leaving the last 10 (which is likely excessive).

feat(plugins): Plugin version pinning

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/plugins/PluginVersionPinningService.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/plugins/ServerGroupPluginVersions.java
front50-core/src/test/groovy/com/netflix/spinnaker/front50/model/plugins/PluginVersionPinningServiceSpec.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PluginVersionController.java

Fixes some Jackson issues and handles those stupid `NotFoundException` checked exceptions that Front50 is so fond of using.

fix(plugins): Serde and API simplication, handling checked exceptions

---

front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3Properties.java

This was being defaulted by Halyard, but will no longer be defaulted by kleat; add this default to front50 so that users using kleat get the same default as Halyard users. This doesn't affect users who explicitly specify it (or Halyard users as Halyard always explicitly defaults the field).

chore(s3): Add deafult rootFolder name

---

front50-gcs/src/main/java/com/netflix/spinnaker/front50/config/GcsProperties.java

This was being defaulted by Halyard, but will no longer be defaulted by kleat; add this default to front50 so that users using kleat get the same default as Halyard users. This doesn't affect users who explicitly specify it (or Halyard users as Halyard always explicitly defaults the field).

chore(gcs): Add deafult rootFolder name

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/plugins/PluginInfoService.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/validator/HasOnePreferredReleaseValidator.java

This should keep us from shooting ourselves in the foot in the future.

fix(plugins): Validate plugin info has at most one preferred release, and cleanup preferred releases when necessary

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/PluginInfoController.java

Danger danger.
We don't want to authz the create endpoints, because anyone can publish a plugin and that's a-ok.

fix(plugins): Authorize destructive plugin mgmt endpoints

---

front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/BulkStorageService.java
front50-core/src/main/groovy/com/netflix/spinnaker/front50/model/StorageServiceSupport.java
front50-sql/src/main/kotlin/com/netflix/spinnaker/front50/model/SqlStorageService.kt
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/v2/EntityTagsController.groovy

This PR also adjusts the bulk import behavior for entity
tags to avoid a one-by-one fetch after the import succeeds.
Given our use-cases, I believe this unnecessarily adds to the
import time.

perf(sql): Support for bulk sql imports

---

front50-web/src/main/groovy/com/netflix/spinnaker/front50/config/Front50WebConfig.groovy
front50-web/src/main/groovy/com/netflix/spinnaker/front50/controllers/v2/ApplicationsController.groovy

In [this PR](https://github.com/spinnaker/front50/pull/619), we added logic to sync roles after an application is created. Let's only attempt to sync roles if the Fiat client is actually enabled. Elsewhere in Front50, such as in ApplicationPermissionsService.syncUsers, we only attempt to call Fiat to sync these roles if FiatClientConfigurationProperties is enabled, if FiatService is present, and if FiatConfigurationProperties.roleSync is enabled. Let's mirror this logic in the ApplicationsController.
cc @AbdulRahmanAlHamali

fix(fiat): only attempt to sync permissions when fiat is enabled

---

front50-core/src/main/java/com/netflix/spinnaker/front50/model/application/ApplicationService.java
front50-core/src/test/groovy/com/netflix/spinnaker/front50/model/application/ApplicationServiceSpec.groovy

I removed this behavior as part of removing the weird in-memory copy behavior
that Applications used thinking it was unnecessary. Turns out front50 allows
patch updates across the entire application model, but there were no tests
covering this feature.

fix(core): Support partial application model updates

---

front50-core/src/main/java/com/netflix/spinnaker/front50/model/plugins/PluginInfoService.java
front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/PluginInfoController.java

This endpoint shouldn't be used much if things are working well, but it can be useful here and there to modify an existing release.  
Admin required.

feat(plugins): Upsert plugin info release endpoint

---

front50-core/src/main/java/com/netflix/spinnaker/front50/model/StorageServiceSupport.java

The exception was right there and I still didn't ignore it.

fix(core): Do not open breaker on NotFoundException

---

front50-core/src/main/java/com/netflix/spinnaker/front50/validator/ApplicationNameValidator.java
front50-core/src/main/java/com/netflix/spinnaker/front50/validator/ApplicationNameValidatorConfigurationProperties.java
front50-core/src/test/groovy/com/netflix/spinnaker/front50/validator/ApplicationNameValidatorSpec.groovy

In case a user submits invalid application name via the API (instead of `deck`), we want to catch bad application names (validation that's in `deck` already)
The validation regex is supplied by config:
```yaml
validation:
appNameValidator:
nameRegEx: "^.*$"
```
By default, no validation will be performed (same as today)

feat(name validation): Add app name validation

---

front50-migrations/src/main/java/com/netflix/spinnaker/front50/migrations/DeleteDanglingServiceAccountsMigration.java
front50-migrations/src/main/java/com/netflix/spinnaker/front50/migrations/RunAsUserToPermissionsMigration.java
front50-migrations/src/test/groovy/com/netflix/spinnaker/front50/migrations/DeleteDanglingServiceAccountsMigrationSpec.groovy

Earlier versions of Front50 did not delete managed service accounts when the corresponding pipeline or application was deleted. This was fixed in PR #769, but that change was not retroactive. This PR adds a migration that will cleanup managed service accounts that are not in use (dangling).

feat(serviceaccounts): Delete dangling service accounts migration

---

front50-migrations/src/main/java/com/netflix/spinnaker/front50/migrations/RunAsUserToPermissionsMigration.java
front50-migrations/src/test/groovy/com/netflix/spinnaker/front50/migrations/RunAsUserToPermissionsMigrationSpec.groovy

Because the migration is already feature flagged, I think there is no need to expire this migration by using a hard coded date.

fix(authz): Activate the RunAsUserToPermissionsMigration again

---

front50-web/front50-web.gradle

kork-runtime brings in kork-swagger for the runtime component configuration

fix(dependencies): depend on only swagger-annotations for compile

---

front50-oracle/front50-oracle.gradle
front50-oracle/src/main/java/com/netflix/spinnaker/front50/model/OracleStorageService.java

Related tickets: spinnaker/spinnaker#5035
This pull request is to introduce changes made that fix an issue related to Oracle Object Storage and the Spinnaker pipeline. Prior to these changes any edits made to the deployment pipeline would not be persisted using Oracle Object Storage. The changes introduced in this PR resolved those issues such that the previous caching issues seem to be gone. The difference can be observed below in the code.

fix(provider/Oracle):Cache issue related to Oracle Object Storage

---

front50-core/src/main/java/com/netflix/spinnaker/front50/model/plugins/PluginEvent.java
front50-core/src/main/java/com/netflix/spinnaker/front50/model/plugins/PluginEventType.java
front50-core/src/main/java/com/netflix/spinnaker/front50/model/plugins/PluginInfo.java
front50-core/src/main/java/com/netflix/spinnaker/front50/model/plugins/PluginInfoDelta.java
front50-core/src/main/java/com/netflix/spinnaker/front50/model/plugins/PluginInfoService.java
front50-core/src/test/groovy/com/netflix/spinnaker/front50/model/plugins/PluginInfoServiceSpec.groovy

This PR fires events directly from Front50 PluginInfoService.  It adds a `PluginEventType` enum which the Plugin Trigger checks in Echo.  I created a `PluginInfoDelta` class that checks for any added or removed releases, and captures the old and new preferred versions.
Initially I was just going to shoehorn the triggering of events into each code path but ended up doing a small refactor.  This PR also consolidates the persistence, validation, and event triggering into a single `savePluginInfo` method.
I also consolidated the management of `preferred` flags into `preferRelease` and made the contract a bit more explicit and a little less side-effecty.  Happy to hear any feedback, since I rarely do teh javas.

refactor(plugins): Send plugin events to echo from front50 instead of igor

---

front50-azure/src/main/java/com/netflix/spinnaker/front50/config/AzureStorageConfig.java
front50-core/src/main/java/com/netflix/spinnaker/front50/config/CommonStorageServiceDAOConfig.java
front50-gcs/src/main/java/com/netflix/spinnaker/front50/config/GcsConfig.java
front50-oracle/src/main/java/com/netflix/spinnaker/front50/config/OracleConfig.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3Config.java
front50-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlConfiguration.kt
front50-sql/src/test/kotlin/com/netflix/spinnaker/config/CompositeStorageServiceConfigurationTests.kt
front50-swift/src/main/java/com/netflix/spinnaker/front50/config/SwiftConfig.java

There's no reason for everyone to subclass this. It just binds a bunch of beans, it doesn't provide any functionality other than that, so just make it a `@Configuration` of its own.

refactor(spring config): simplify the DAO config

---

README.md

This PR fixes the broken markdown tables in README.md.
*Before*:
*After*:

fix(docs): update broken markdown table

---

front50-core/src/main/java/com/netflix/spinnaker/front50/model/plugins/PluginInfo.java
front50-core/src/main/java/com/netflix/spinnaker/front50/model/plugins/remote/RemoteExtension.java
front50-core/src/main/java/com/netflix/spinnaker/front50/model/plugins/remote/stage/StageRemoteExtensionConfig.java
front50-core/src/test/groovy/com/netflix/spinnaker/front50/model/plugins/PluginInfoServiceSpec.groovy

In https://github.com/spinnaker/orca/pull/3840 I realized I had the cart before the horse on a few items, specifically the basic remote extension point configuration.  This will not only allow me to get away from abusing the PreconfiguredJob stuff even more (by allowing for specific remote stage configuration), but also lay some of the ground work for other types of remote extension points.
Adds a `remoteExtensions` field to a plugin info `release`.  A plugin that is just a remote extension look like this:
```
{
"id": "netflix.remote",
"description": "A remote plugin",
"provider": "csmalley",
"releases": [
{
"version": "0.0.1",
"date": "2020-06-16T02:20:14.889Z",
"requires": "orca>=1.0.0",
"url": null,
"sha512sum": null,
"preferred": false,
"lastModified": "2020-06-18T23:08:48.899Z", …
```

feat(plugins): Add remote extensions field to a plugin info release

---

front50-gcs/src/main/java/com/netflix/spinnaker/front50/config/GcsProperties.java
front50-gcs/src/test/kotlin/com/netflix/spinnaker/front50/model/FakeStorageRpc.kt
front50-gcs/src/test/kotlin/com/netflix/spinnaker/front50/model/GcsIntegrationTest.kt
front50-gcs/src/test/kotlin/com/netflix/spinnaker/front50/model/GcsIntegrationTestConfiguration.kt
front50-gcs/src/test/kotlin/com/netflix/spinnaker/front50/model/TestGcsStorageService.kt
front50-gcs/src/test/resources/minimal-gcs-account.yml

Fixes spinnaker/spinnaker#6000.
* test(gcs): Add some implementations to FakeStorageRpc
In an upcoming commit, we'll need to also support getting a bucket; to prepare for that let's update the FakeStorageRpc to:
* Keep track of what bucket objects are in (rather than now where it assumes they are all in the same bucket)
* Handle creating and getting a bucket
We'll add an additional Map around the blobs data structure that maps the bucket to a Map of blobs.  (This is a bit of a complex data structure that in production code might be better expressed as classes, but for this single fake in a test it's porbably fine.)
Creating a bucket initializes its blobs to an empty map; we know if a bucket exists by whether it has an entry in the map.
I used the documentation on the interface we're …

fix(gcs): Fix startup error when bucketLocation is not specified

---

front50-web/src/main/java/com/netflix/spinnaker/front50/config/Front50WebConfig.java

Based on @jonsie's comment in https://github.com/spinnaker/front50/pull/949, I thought "of course Front50 is pluggable, we've written Front50 plugins!". 
It's true that Armory has written Front50 plugins and that they work for some range of Spinnaker versions, but it's also true that Front50 doesn't import `PluginsAutoConfiguration`, which is pretty confusing. 
It turns out that since `kork-plugins` ends up on the [classpath](https://github.com/spinnaker/front50/blob/master/front50-core/front50-core.gradle#L31) and since Front50 `Main` does a component scan of `com.netflix.spinnaker.config`, we used to get `PluginsAutoConfiguration` for free. I think we lost that behavior when the `@Configuration` annotation on `PluginsAutoConfiguration` [got dropped …

feat(plugins): make Front50 pluggable

---

front50-api-tck/README.md
front50-api-tck/front50-api-tck.gradle
front50-api-tck/src/main/kotlin/com/netflix/spinnaker/front50/api/test/Front50Fixture.kt
front50-api-tck/src/main/resources/front50-test-app.yml
front50-api-tck/src/test/kotlin/com/netflix/spinnaker/front50/api/test/Front50FixtureTest.kt
settings.gradle

This is modeled after https://github.com/spinnaker/orca/tree/master/orca-api-tck and has the same purpose (letting plugin developers write Front50 integration tests).
I named the project `front50-api-tck`, following the pattern in Orca (and I'm opening PRs for test fixtures in the other projects). There's no corresponding `front50-api` subproject, which makes the name seem a little strange.

feat(test): add front50 test fixture

---

front50-core/src/main/java/com/netflix/spinnaker/front50/model/Timestamped.java
front50-core/src/main/java/com/netflix/spinnaker/front50/model/application/Application.java
front50-sql/src/main/kotlin/com/netflix/spinnaker/front50/model/SqlStorageService.kt
front50-sql/src/test/kotlin/com/netflix/spinnaker/front50/model/SqlStorageServiceTests.kt

For historical reasons, the original `createTs` value on the Application object itself
is not reliably stored.
When sql backends are used, the `created_at` column is the most accurate representation
of the time at which an Application was created.
This PR will override any `createTs` value that happens to exist in the Application
json blob with the value of the db column.

fix(sql): Ensure that `Application.createTs` is reliably returned when sql is used

---

front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3BucketProperties.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3ClientFactory.java

Allow users to override the S3 signer algorithm if they can't use the default. They can set the AWS client to use a different algorithm in their profile yaml:
```
s3:
bucket: my-bucket
rootFolder: front50
region: us-west-2
enabled: true
signerOverride: S3SignerType
```
The AWS SDK validates the algorithm passed in and will throw an exception if the user tries to configure one that doesn't exist:
```
Caused by: java.lang.IllegalArgumentException: unknown signer type: blahblah
at com.amazonaws.auth.SignerFactory.createSigner(SignerFactory.java:131) ~[aws-java-sdk-core-1.11.934.jar:na]
at com.amazonaws.auth.SignerFactory.getSignerByTypeAndService(SignerFactory.java:104) ~[aws-java-sdk-core-1.11.934.jar:na]
at com.amazonaws.AmazonWebServiceClient.computeSignerByServiceRegion(AmazonWebServiceCl …
```

feat(s3): add signerOverride config option

---

front50-migrations/src/main/java/com/netflix/spinnaker/front50/migrations/SpelLoadBalancersMigration.java

Remove spelLoadBalancers and spelTargetGroups from all deploy stages' clusters objects.
Companion PR to https://github.com/spinnaker/deck/pull/8957

feat(migrations): Add spelLoadBalancersMigration

---

front50-core/src/main/java/com/netflix/spinnaker/front50/model/StorageServiceSupport.java

Removes the unexpected stale read warning. This isn't really useful and doesn't play nicely with providers that don't have millisecond precision - using S3 and this log is being generated millions of times an hour.
resolves spinnaker/spinnaker#4093
cc @ajordens @dogonthehorizon @german-muzquiz

fix(core): remove stale read warning

---

front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3BucketProperties.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3ClientFactory.java

Adds option (disabled by default) to enable payload signing. This is required for Signature V4.
cc @ajordens @german-muzquiz

feat(s3): allow enabling payload signing

---

front50-api/src/main/java/com/netflix/spinnaker/front50/api/model/pipeline/Pipeline.java
front50-azure/src/main/java/com/netflix/spinnaker/front50/model/AzureStorageService.java
front50-core/src/test/groovy/com/netflix/spinnaker/front50/model/pipeline/PipelineSpec.groovy
front50-gcs/src/main/java/com/netflix/spinnaker/front50/config/GcsConfig.java
front50-migrations/src/main/java/com/netflix/spinnaker/front50/migrations/V2PipelineTemplateSourceToArtifactMigration.java
front50-oracle/src/main/java/com/netflix/spinnaker/front50/model/OracleStorageService.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/config/S3Config.java
front50-s3/src/main/java/com/netflix/spinnaker/front50/model/S3StorageService.java
front50-swift/src/main/java/com/netflix/spinnaker/front50/model/SwiftStorageService.java

This PR resolves this issue: https://github.com/spinnaker/spinnaker/issues/6468
This was introduced when I migrated Pipeline and Timestamped to a new front50-api package here: spinnaker/front50#1035
I needed to add the new Pipeline and Timestamped mixins to the other object mappers used for deserialization in the storage service classes.
There were also a few pipeline properties that were missing that needed to be added: https://github.com/spinnaker/front50/blob/9ed6b52419a4d154d7d86b5cbf54b9a2d3104f53/front50-web/src/main/resources/graphql/pipelineConfig.graphqls#L12

fix(storage): Fix deserialization regression for storage services

---

front50-core/src/main/java/com/netflix/spinnaker/front50/jackson/mixins/PipelineMixins.java
front50-core/src/test/groovy/com/netflix/spinnaker/front50/model/pipeline/PipelineSpec.groovy

This deserialization regression was introduced when I migrated the the `@jsonIgnore` annotations for the getter/setters in the `front50-core` Pipeline class to `@JsonIgnoreProperties` on the PipelineMixin class here: spinnaker/front50#1035. 
I got reports that pipelines were still producing errors due to missing fields and that the fields that we were supposed to ignore actually needed to be serialized/deserialized (ie name, application, etc).  I checked out the previous code prior to the `front50-api` package creation PR and noticed that the `@jsonIgnore` field was masking behavior and wasn't actually ignoring those fields for serialization/deserialization. 
Introducing `@JsonIgnoreProperties` to the PipelineMixin class enforced the behavior of ignoring these fields, so I need to revert …

fix(api): remove JsonIgnore annotations to fix Pipeline deserialization regression

---

front50-api/src/main/java/com/netflix/spinnaker/front50/api/model/pipeline/Pipeline.java
front50-core/src/main/java/com/netflix/spinnaker/front50/jackson/mixins/PipelineMixins.java
front50-core/src/test/groovy/com/netflix/spinnaker/front50/model/application/ApplicationModelSpec.groovy
front50-core/src/test/groovy/com/netflix/spinnaker/front50/model/pipeline/PipelineSpec.groovy

This is a regression from refactoring the Pipeline class that was moved to the `front50-api` package in #1035. This PR reverts the Pipeline object to previous behavior where null values for some properties are ignored during serialization. Also, this removes the `lastModified` property from serialization since that was the previous behavior and it is a duplicate of `updateTs`.

fix(api): fix regression for ignoring specific pipeline fields with null values

---

front50-api/src/main/java/com/netflix/spinnaker/front50/api/model/pipeline/Pipeline.java
front50-core/src/main/java/com/netflix/spinnaker/front50/jackson/mixins/PipelineMixins.java
front50-core/src/test/groovy/com/netflix/spinnaker/front50/model/pipeline/PipelineSpec.groovy

#1043 annotated some properties that needed to be excluded if they were null, but we are finding that all of these properties need to be excluded if they are null or there will be null pointer exceptions in Orca.

fix(api): ignore all Pipeline properties with null value for serialization

---

front50-api/src/main/java/com/netflix/spinnaker/front50/api/model/pipeline/Pipeline.java
front50-core/src/main/java/com/netflix/spinnaker/front50/jackson/mixins/PipelineMixins.java
front50-core/src/test/groovy/com/netflix/spinnaker/front50/model/pipeline/PipelineSpec.groovy

Pipeline properties that were migrated to the front50-api package as booleans should actually be strings, since this was the previous behavior (ie true -> "true", false -> "false). This PR reverts these properties back.

fix(api): Fix type mismatch with Pipeline boolean properties

---

front50-sql-postgres/front50-sql-postgres.gradle

[CVE-2020-13692](https://nvd.nist.gov/vuln/detail/CVE-2020-13692)

fix(vulnerability): Remove fixed version of postgres dependency to accommodate safer version from kork.

---

front50-api/src/main/java/com/netflix/spinnaker/front50/api/model/pipeline/Pipeline.java
front50-core/src/main/java/com/netflix/spinnaker/front50/jackson/mixins/PipelineMixins.java
front50-core/src/test/groovy/com/netflix/spinnaker/front50/model/pipeline/PipelineSpec.groovy

The original type for these properties on deck is defined as boolean so we should keep it as is.

fix(api): revert fix type mismatch regression with Pipeline boolean properties (#1046)

---

front50-api/src/main/java/com/netflix/spinnaker/front50/api/model/pipeline/Pipeline.java
front50-core/src/main/java/com/netflix/spinnaker/front50/jackson/mixins/PipelineMixins.java
front50-web/src/main/resources/graphql/pipelineConfig.graphqls
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/PipelineControllerTck.groovy

It adds support for max concurrent pipeline executions. If concurrent pipeline execution is enabled, pipelines will queue when the max concurrent pipeline executions is reached. Any queued pipelines will be allowed to run once the number of running pipeline executions drops below the max. If the max is set to 0, then pipelines will not queue.
This is the proposed change for spinnaker/spinnaker#6558.
Changes to orca, deck and echo are also needed in order to expose max concurrent pipeline executions as a pipeline configuration to Spinnaker users.
(Orca pull request: https://github.com/spinnaker/orca/pull/4193)
(Echo pull request: https://github.com/spinnaker/echo/pull/1134)
(Deck pull request: https://github.com/spinnaker/deck/pull/9777)

feat(pipeline executions/front50): Add support for max concurrent pipeline executions

---

front50-core/src/main/java/com/netflix/spinnaker/front50/model/application/ApplicationDAO.java
front50-core/src/test/groovy/com/netflix/spinnaker/front50/model/application/ApplicationDAOSpec.groovy

Fixes searching for applications by keys with caps in the dataset, such as `repoSlug`.

fix(core): do not lowercase search params

---

front50-oracle/front50-oracle.gradle

While enforcing the direct and transitive dependencies strictly from kork-bom using "enforcedPlatform" in build.gradle as:
implementation(enforcedPlatform("io.spinnaker.kork:kork-bom:$korkVersion"))
oci-java-sdk-bom:1.5.17 is overriding the oci-java-sdk-objectstorage:1.19.1 (transitive dependency) version, which is an older version coming from kork-bom mentioned in [spinnaker-dependencies.gradle](https://github.com/spinnaker/kork/blob/bdfef2b6998bce67d611765c5e40634e380ee32a/spinnaker-dependencies/spinnaker-dependencies.gradle#L67).
It is causing an error in front50-oracle module as given below:
```
> Task :front50-oracle:compileJava
/home/ubuntu/spinnaker-comp/sb-upgrade-2-3-12/front50/front50-oracle/src/main/java/com/netflix/spinnaker/front50/model/OracleStorageService.java:232: error: …
```

fix(dependency): Forcing oci-java-sdk-objectstorage version for desired conflict resolution.

---

front50-gcs/front50-gcs.gradle

While enforcing the direct and transitive dependencies strictly from kork-bom using "enforcedPlatform" in build.gradle as:
implementation(enforcedPlatform("io.spinnaker.kork:kork-bom:$korkVersion"))
google-api-services-storage:v1-rev141-1.25.0 and google-auth-library-oauth2-http:0.18.0 is overriding the google-api-services-storage:v1-rev20200326-1.30.9 and google-auth-library-oauth2-http:0.20.0 version, which is an older version coming from kork-bom mentioned in spinnaker-dependencies.gradle.
It is causing following errors in front50-gcs module as given below:
```
> Task :front50-gcs:compileTestKotlin FAILED
e: /home/ubuntu/spinnaker-comp/sb-upgrade-2-3-12/front50/front50-gcs/src/test/kotlin/com/netflix/spinnaker/front50/model/FakeStorageRpc.kt: (23, 46): Unresolved reference: HmacKey
e: …
```

fix(dependency): Forcing google-api-services-storage and google-auth-library-oauth2-http version for desired conflict resolution

---

front50-api/src/main/java/com/netflix/spinnaker/front50/api/model/pipeline/Pipeline.java

Add back the last modified timestamp property `updateTs` to pipelines, which is expected by things like deck to provide revision history.

fix(pipeline): include updated timestamp

---

front50-api/src/main/java/com/netflix/spinnaker/front50/api/model/pipeline/Pipeline.java
front50-sql/src/main/kotlin/com/netflix/spinnaker/front50/model/SqlStorageService.kt

**Observed Behavior**
**Expected Behavior**
**Issue reason**
Desk uses this request to update pipeline.
POST http://{host}:8084/pipelines?staleCheck=true
```
payload {
"id": string,
"name": string,
"application": string,
"schema": string,
"triggers": [],
"index": number,
"updateTs": "1659026349611",
"lastModifiedBy": string,
"stages": object[],
"keepWaitingPipelines": bolean,
"limitConcurrent": bolean,
"spelEvaluator": string
}
```
As you can see, it has `updateTs` field inside the payload, so we need to have setter function to deserialize this DTO correctly.

fix: Revision history is not showing the timestamp of the revision

---

front50-api/src/main/java/com/netflix/spinnaker/front50/api/model/pipeline/Pipeline.java
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/PipelineControllerSpec.groovy

**What?**
`updateTs` field is missing in the response of `GET {host}/pipelines/{pipelineId}/history` endpoint. As a result, the pipeline revision history is not showing the timestamp of the revision.

fix(updateTs): missing updateTs field in the get pipeline history's response.

---

front50-core/src/main/java/com/netflix/spinnaker/front50/ServiceAccountsService.java
front50-core/src/main/java/com/netflix/spinnaker/front50/config/FiatConfigurationProperties.java
front50-core/src/test/groovy/com/netflix/spinnaker/front50/ServiceAccountsServiceSpec.groovy

This PR follows on from https://github.com/spinnaker/fiat/pull/961. Main goal is described in that PR. This PR is mainly to demonstrate how that endpoint will be used.
I've added a config value `isDisableRoleSyncWhenSavingServiceAccounts` which can be used to opt-in to this behaviour, making this change quite safe to release.
I will add tests and make sure the build is green once the other PR is merged, as this change depends on a release of `fiat-api` for that new endpoint added. 
Thanks.

perf(serviceAccounts): Add attribute that allows creating service accounts without running full role syncs

---

front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/PipelineController.java
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/PipelineControllerSpec.groovy

We've noticed that sometimes spinnaker users end up with duplicated pipelines when using pipelines as a code. In my opinion the logic in PipelineController that creates a pipeline is not safe in a multithreaded environment as we validate pipeline duplicates in line 151, but we actually persist it in line 165. It's likely that two threads running simultaneously will pass validation due to lack of duplicates and then they will persist it.
This simple fix prevents from aforementioned scenario.

fix(pipelines): prevent from creating duplicated pipelines

---

front50-core/src/main/java/com/netflix/spinnaker/front50/validator/pipeline/KubernetesBlueGreenStrategyValidator.java
front50-core/src/test/groovy/com/netflix/spinnaker/front50/validator/pipeline/KubernetesBlueGreenStrategyValidatorSpec.groovy
front50-web/src/main/java/com/netflix/spinnaker/front50/config/Front50WebConfig.java

With other PRs we've introduced blue/green strategy as this is a terminology used more often in the industry compared to the Neflix-specific phrasing. The first step is to deprecate redblack. When creating new pipelines using fron50 API, if traffic management is enabled and redblack is used a warning message is logged.
In the future, after the redblack will be completely removed and validation error will be returned
Related PRs: 
https://github.com/spinnaker/deck/pull/9911
https://github.com/spinnaker/clouddriver/pull/5811
https://github.com/spinnaker/orca/pull/4332

feat(pipeline/kubernetes): Introduce validator for kubernetes blue/greeen traffic management strategy

---

.github/workflows/build.yml
.github/workflows/pr.yml
.github/workflows/release.yml

to stay up to date, and to remove some deprecation warnings like:
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecatin>

chore(gha): bump versions of github actions

---

front50-web/front50-web.gradle

The property spring.config.additional-location is redundant in front50-web.gradle file. This property is set by class com.netflix.spinnaker.kork.boot.DefaultPropertiesBuilder in com.netflix.spinnaker.front50.Main. So removing it from gradle file.

refactor(web): Clean up redundant spring property in gradle file

---

front50-redis/front50-redis.gradle
front50-test/front50-test.gradle

with a specific goal to get `org.testng:testng:7.4.0` out of shipping code, since it's vulnerable to CVE-2022-4065.

chore(dependencies): remove dependency on groovy-all where straightforward

---

front50-migrations/src/main/java/com/netflix/spinnaker/front50/migrations/RedBlackToBlueGreenK8sPipelinesMigration.java
front50-migrations/src/test/groovy/com/netflix/spinnaker/front50/migrations/RedBlackToBlueGreenK8sPipelinesMigrationSpec.groovy

Migrate existing K8s deploy manifest traffic management from redblack to bluegreen
The migration loads all the k8s pipelines that are currently using red/black traffic management, and it is updating all pipelines to the new terminology blue/green
Pipeline inserted in MySQL using **redblack** strategy
After the migration, the strategy will be **bluegreen**

feat(pipeline/kubernetes): Migrate existing K8s deploy manifest traffic management from redblack to bluegreen

---

front50-sql/src/main/kotlin/com/netflix/spinnaker/config/CompositeStorageServiceConfiguration.kt
front50-sql/src/main/kotlin/com/netflix/spinnaker/front50/migrations/StorageServiceMigrator.kt
front50-sql/src/test/kotlin/com/netflix/spinnaker/front50/migrations/StorageServiceMigratorTests.kt

The `writeOnly` flag is currently unused, so repurposing it to toggle disabling deletion of "orphaned" objects in the target datasource.
Useful when "merging" two disparate instances of Spinnaker together.

feat(migration): ability to disable deleting orphaned objects

---

build.gradle
front50-api-tck/front50-api-tck.gradle
front50-gcs/front50-gcs.gradle
front50-sql/front50-sql.gradle

Cleaning up the call for test engines using `useJUnitPlatform()` from individual sub-modules, and placing it in build.gradle at root. As per the gradle docs, all test engines on the test runtime classpath will be used by sub modules. 
https://docs.gradle.org/6.8.1/userguide/java_testing.html#filtering_test_engine
Spring boot 2.4.x removed JUnit5 vintage engine from spring-boot-starter-test.
[https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.4-Release-Notes#junit-5s-vintage-engine-removed-from-spring-boot-starter-test]
It is required for executing junit4 based test cases in front50.
So, introducing junit-vintage-engine dependency in build.gradle, using testRuntimeOnly() as suggested in section 3.1 of https://junit.org/junit5/docs/5.6.2/user-guide/index.pdf
Total test cases …

chore(tests): Cleanup of useJUnitPlatform() from sub-modules and introducing junit-vintage-engine in front50

---

front50-core/src/main/java/com/netflix/spinnaker/front50/config/CommonStorageServiceDAOConfig.java
front50-core/src/main/java/com/netflix/spinnaker/front50/config/StorageServiceConfigurationProperties.java
front50-core/src/main/java/com/netflix/spinnaker/front50/model/StorageService.java
front50-core/src/main/java/com/netflix/spinnaker/front50/model/StorageServiceSupport.java
front50-core/src/main/java/com/netflix/spinnaker/front50/model/application/DefaultApplicationDAO.java
front50-core/src/main/java/com/netflix/spinnaker/front50/model/application/DefaultApplicationPermissionDAO.java
front50-core/src/main/java/com/netflix/spinnaker/front50/model/delivery/DefaultDeliveryRepository.java
front50-core/src/main/java/com/netflix/spinnaker/front50/model/notification/DefaultNotificationDAO.java
front50-core/src/main/java/com/netflix/spinnaker/front50/model/pipeline/DefaultPipelineDAO.java
front50-core/src/main/java/com/netflix/spinnaker/front50/model/pipeline/DefaultPipelineStrategyDAO.java
front50-core/src/main/java/com/netflix/spinnaker/front50/model/pipeline/DefaultPipelineTemplateDAO.java
front50-core/src/main/java/com/netflix/spinnaker/front50/model/plugins/DefaultPluginInfoRepository.java
front50-core/src/main/java/com/netflix/spinnaker/front50/model/plugins/DefaultPluginVersionPinningRepository.java
front50-core/src/main/java/com/netflix/spinnaker/front50/model/project/DefaultProjectDAO.java
front50-core/src/main/java/com/netflix/spinnaker/front50/model/serviceaccount/DefaultServiceAccountDAO.java
front50-core/src/main/java/com/netflix/spinnaker/front50/model/snapshot/DefaultSnapshotDAO.java
front50-core/src/main/java/com/netflix/spinnaker/front50/model/tag/DefaultEntityTagsDAO.java
front50-gcs/src/main/java/com/netflix/spinnaker/front50/config/GcsConfig.java
front50-sql/src/main/kotlin/com/netflix/spinnaker/front50/model/SqlStorageService.kt
front50-sql/src/test/kotlin/com/netflix/spinnaker/front50/model/SqlStorageServiceTests.kt
front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/PipelineController.java
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/NotificationControllerTck.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/PipelineControllerTck.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/StrategyControllerTck.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/v2/ApplicationsControllerTck.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/v2/ProjectsControllerTck.groovy

This PR adds three new config flags to [each object type under service-storage](https://github.com/spinnaker/front50/blob/f6452ec07f207246b3ee940c49d31a115886d4a3/front50-core/src/main/java/com/netflix/spinnaker/front50/config/StorageServiceConfigurationProperties.java#L9-L20).
One is fairly mechanical:
* cacheHealthCheckTimeoutSeconds: previously hard-coded to 90
The other two are performance improvements.  They default to false.
* synchronizeCacheRefresh: When true, if multiple threads attempt to refresh the cache in StorageServiceSupport simultaneously, only one actually does the refresh.  The others wait until it's complete.  This reduces load on the data store.
* optimizeCacheRefreshes: When true, for objects that support versioning, cache refreshes only query the data store for …

feat(core + sql): Optimize cache refresh

---

front50-core/src/main/java/com/netflix/spinnaker/front50/model/pipeline/DefaultPipelineDAO.java
front50-core/src/main/java/com/netflix/spinnaker/front50/model/pipeline/PipelineDAO.java
front50-redis/src/main/groovy/com/netflix/spinnaker/front50/redis/RedisPipelineDAO.groovy
front50-redis/src/test/groovy/com/netflix/spinnaker/front50/redis/RedisPipelineDAOSpec.groovy
front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/PipelineController.java
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/PipelineControllerSpec.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/PipelineControllerTck.groovy

so it's possible for consumers of pipelines (e.g. echo) to get only the information they need.
enabledPipelines: boolean -- only return enabled/disabled pipelines
enabledTriggers: boolean -- only return pipelines with at least one enabled trigger
triggerTypes: only return pipelines with a trigger whose type is present in this comma-separated string of trigger types
for example GET /pipelines?enabledPipelines=true&enabledTriggers=true&triggerTypes=foo,bar
which, with correct URL-encoding is:
GET /pipelines?enabledPipelines=true&enabledTriggers=true&triggerTypes=foo%2Cbar
Note that if both enabledTriggers and triggerTypes are specified, that a single trigger must satisfy both conditions for front50 to return its pipeline.
Also add a GET /pipelines/{application}/name/{name} endpoint which …

feat(web): add optional query params to the GET /pipelines endpoint

---

front50-core/src/main/java/com/netflix/spinnaker/front50/validator/pipeline/KubernetesBlueGreenStrategyValidator.java
front50-core/src/test/groovy/com/netflix/spinnaker/front50/validator/pipeline/KubernetesBlueGreenStrategyValidatorSpec.groovy

If no traffic management is defined in a K8S deploy manifest pipeline, the validator throws an NPE when trying to check if trafficManagement is enabled.

fix(validator): Fix NPE when traffic management is not defined in a deployment manifest

---

front50-gcs/front50-gcs.gradle
front50-oracle/front50-oracle.gradle

While executing the build script with --warning-mode=fail received below error:
```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0
```
And the deprecated gradle features are:
```
> Configure project :front50-gcs
Using force on a dependency has been deprecated. This is scheduled to be removed in Gradle 7.0. Consider using strict version constraints instead (version { strictly ... } }). Consult the upgrading guide for further information: https://docs.gradle.org/6.8.1/userguide/upgrading_version_5.html#forced_dependencies
at front50_gcs_93cicf1icrojzycbnu0sn2y0i$_run_closure1$_closure2.doCall(/front50/front50-gcs/front50-gcs.gradle:25)
(Run with --stacktrace to get the full stack trace of this deprecation warning.)
> Configure project …
```

refactor(deprecation): remove deprecated gradle constructs/features from front50 in order to upgrade gradle 7

---

front50-migrations/src/main/java/com/netflix/spinnaker/front50/migrations/RedBlackToBlueGreenK8sPipelinesMigration.java
front50-migrations/src/test/groovy/com/netflix/spinnaker/front50/migrations/RedBlackToBlueGreenK8sPipelinesMigrationSpec.groovy

Pipelines created outside of the UI Pipeline Builder may not have stages defined in the JSON. When such a pipeline exists and the `RedBlackToBlueGreenK8sPipelinesMigration` is run the result is an NPE.  This fixes that NPE.

fix(migrations): do not migrate redblack pipelines without stages

---

front50-core/src/main/java/com/netflix/spinnaker/front50/model/ItemDAO.java
front50-core/src/main/java/com/netflix/spinnaker/front50/model/StorageService.java
front50-core/src/main/java/com/netflix/spinnaker/front50/model/StorageServiceSupport.java
front50-sql/src/main/kotlin/com/netflix/spinnaker/config/Front50SqlProperties.kt
front50-sql/src/main/kotlin/com/netflix/spinnaker/config/SqlConfiguration.kt
front50-sql/src/main/kotlin/com/netflix/spinnaker/front50/model/SqlStorageService.kt
front50-sql/src/test/kotlin/com/netflix/spinnaker/front50/model/SqlStorageServiceTests.kt
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/NotificationControllerTck.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/PipelineControllerTck.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/StrategyControllerTck.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/v2/ApplicationsControllerTck.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/v2/ProjectsControllerTck.groovy

that controls how often the health endpoint refreshes information when using sql.  It defaults to 30 seconds to match the behavior before this change.
Information about cache status for each object type (e.g. pipelines, applications, etc.) contributes to the response from front50's /health endpoint.  This change makes it possible to reduce the likelihood that the cache has refreshed, but the response from the /health endpoint doesn't reflect that.

feat(sql): add configuration property sql.healthIntervalMillis

---

front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/PipelineController.java
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/PipelineControllerTck.groovy

in PipelineController.getTriggeredPipelines to avoid a NullPointerException.

fix(web): check trigger.getType() for null before invoking equals method

---

front50-core/src/main/java/com/netflix/spinnaker/front50/model/StorageServiceSupport.java
front50-core/src/test/java/com/netflix/spinnaker/front50/model/StorageServiceSupportTest.java

Even though it seems like the existing filters on items coming back from the database would make this unnecessary, given that existingItems starts empty and, from what I can tell, only contains (filtered) items from the database.
We've seen this happen in production though.  With any luck the logging will help us figure out why.

fix(core): skip existing items with null ids in StorageServiceSupport.fetchAllItemsOptimized

---

.github/workflows/build.yml
.github/workflows/pr.yml
.github/workflows/release.yml
Dockerfile.java11.slim
Dockerfile.java11.ubuntu
Dockerfile.ubuntu

Default containers will use JRE 17. Versions using JRE 11 will also be published to allow opting out if required.

chore(build): update default containers to JRE 17

---

build.gradle
front50-gcs/front50-gcs.gradle

With reference to the spinnaker issue https://github.com/spinnaker/spinnaker/issues/6866, google-api-services-storage dependency version (v1-rev20200326-1.30.9) is not forced by front50-gcs module to other front50 modules like front50-web and it is leaked by kork-secret-gcp module (v1-rev141-1.25.0) to front50 modules.
```
$ ./gradlew front50-web:dI --dependency google-api-services-storage --configuration runtimeClasspath
> Task :front50-web:dependencyInsight
com.google.apis:google-api-services-storage:v1-rev141-1.25.0
Variant runtime:
| Attribute Name                 | Provided     | Requested    |
|--------------------------------|--------------|--------------|
| org.gradle.status              | release      |              |
| org.gradle.category            | library      | library …
```

fix(dependency): fix dependency version leak of google-api-services-storage from kork in front50-web

---

front50-core/src/test/groovy/com/netflix/spinnaker/front50/plugins/CachingPluginBinaryStorageServiceSpec.groovy

This change would make code less dependent on groovy upgrades. 
Test coverage remain same before and after refactor (Tests executed 305).

refactor(core/test): refactor NioGroovyMethods.readBytes() to use java.nio.file.Files

---

front50-web/front50-web.gradle

While upgrading groovy 3.0.10 and spockframework 2.0-groovy-3.0, groovy-json is not part of [spockframework](https://mvnrepository.com/artifact/org.spockframework/spock-core/2.0-groovy-3.0) and encounter below error during test compilation:
```
startup failed:
/front50/front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/PipelineControllerTck.groovy: 42: unable to resolve class groovy.json.JsonSlurper
@ line 42, column 1.
import groovy.json.JsonSlurper
^
1 error
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':front50-web:compileTestGroovy'.
```
So, adding explicit dependency of groovy-json in front50-web.gradle.
With groovy 2.5.15 and spockframework 1.3-groovy-2.5, groovy-json appear as transitive dependency of …

chore(dependency): add explicit dependency of groovy-json in front50-web while upgrading groovy 3.x

---

front50-gcs/src/test/kotlin/com/netflix/spinnaker/front50/model/GcsIntegrationTest.kt

While upgrading spring boot 2.6.15, encounter below error in front50-gcs module during test compilation:
```
> Task :front50-gcs:compileTestKotlin FAILED
e: /front50/front50-gcs/src/test/kotlin/com/netflix/spinnaker/front50/model/GcsIntegrationTest.kt: (28, 46): Unresolved reference: ConfigFileApplicationContextInitializer
e: /front50/front50-gcs/src/test/kotlin/com/netflix/spinnaker/front50/model/GcsIntegrationTest.kt: (39, 18): Only 'const val' can be used in constant expressions
e: /front50/front50-gcs/src/test/kotlin/com/netflix/spinnaker/front50/model/GcsIntegrationTest.kt: (39, 19): Unresolved reference: ConfigFileApplicationContextInitializer
e: /front50/front50-gcs/src/test/kotlin/com/netflix/spinnaker/front50/model/GcsIntegrationTest.kt: (39, 19): An annotation argument must be a …
```

refactor(gcs/test): replace deprecated test application context initializer class during upgrade to spring boot 2.6.x

---

front50-core/src/main/java/com/netflix/spinnaker/front50/model/StorageService.java
front50-sql/src/main/kotlin/com/netflix/spinnaker/front50/model/SqlStorageService.kt
front50-sql/src/test/kotlin/com/netflix/spinnaker/front50/model/SqlStorageServiceTests.kt

and return the valid ones.  This allows the cache to populate and gives the health check a chance to succeed.
No, it's not supposed to be possible for bad pipelines to make it to the database, but...things happen.

fix(sql): teach SqlStorageService.loadObjects and loadObjectsNewerThan to skip invalid objects

---

front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/PipelineController.java
front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/StrategyController.java
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/PipelineControllerTck.groovy

https://github.com/spinnaker/front50/pull/1035/files#diff-9b514be177faf5444c86a88ab6bb9e6a0add032bfa67862bc8e33b17c4bb9cc9L159 removed it, but [orca's SavePipelineTask](https://github.com/spinnaker/orca/blob/2a2110d849bc50b2497e40554fead7a67abcf8ee/orca-front50/src/main/java/com/netflix/spinnaker/orca/front50/tasks/SavePipelineTask.java#L95) still sets it.
with some little refactors along the way.

fix(web): restore check for regenerateCronTriggerIds in PipelineController.save

---

front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/PipelineController.java

and use an additional filter to clean up the code.
With [pipeline.getTriggers()](https://github.com/spinnaker/front50/pull/1035/files#diff-0b2bc300fd3965c64ba4184955384aa8609cace04e1c015b31ef4a83552e53d1R36) implemented as an accessor, ensureCronTriggersHaveIdentifier was already mutating the pipeline.  Let's make that more obvious by making it return void and adding some javadoc.

refactor(web): change ensureCronTriggersHaveIdentifier to return void

---

front50-migrations/front50-migrations.gradle
front50-migrations/src/main/java/com/netflix/spinnaker/front50/migrations/MigrationRunner.java
front50-migrations/src/test/groovy/com/netflix/spinnaker/front50/config/MigrationConfigTest.java
front50-migrations/src/test/groovy/com/netflix/spinnaker/front50/migrations/MigrationRunnerSpec.groovy

The current implementation of the MigrationRunner is initialized before any migrations in plugins are initialized, and they are therefore not included by the runner. Even if the plugin migrations are defined using `@ExposeToApp`, the beans are never picked up by the MigrationRunner bean. This PR changes the MigrationRunner to look up Migration beans directly from the applicationContext on every run, and will also delay the first run with 10 seconds in order to give some time for plugins to be initialized.

feat(migrations): Support for migrations defined in plugins

---

front50-sql-mysql/front50-sql-mysql.gradle

Before:
```
$ ./gradlew front50-sql-mysql:dI --dependency mysql-connector-java --configuration runtimeClasspath
> Task :front50-sql-mysql:dependencyInsight
mysql:mysql-connector-java:8.0.33
Variant runtime:
| Attribute Name                 | Provided     | Requested    |
|--------------------------------|--------------|--------------|
| org.gradle.status              | release      |              |
| org.gradle.category            | library      | library      |
| org.gradle.libraryelements     | jar          | jar          |
| org.gradle.usage               | java-runtime | java-runtime |
| org.gradle.dependency.bundling |              | external     |
| org.gradle.jvm.environment     |              | standard-jvm |
| org.gradle.jvm.version         |              | 11           | …
```

chore(dependency): unpin mysql-connector-java

---

front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/V2PipelineTemplateController.java
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/V2PipelineTemplateControllerSpec.groovy

This fixes the bug regarding `/v2/pipelineTemplates/<pipeline-template-id>/dependentPipelines` API.
Original Issue: https://github.com/spinnaker/spinnaker/issues/6472
Spinnaker: `1.33.0+`
Front50: `us-docker.pkg.dev/spinnaker-community/docker/front50:2.31.0`
Given a `templateId`, the `getDependentConfigs` method called by `listDependentPipelines` method, was returning `null` for pipeline configuration, causing the entire API to return `[]` even if a specific pipeline template had dependent pipelines.. This seems to be because of 👇 change.
```java
import com.netflix.spinnaker.front50.model.pipeline.TemplateConfiguration;
TemplateConfiguration v1Config = objectMapper.convertValue(templatedPipeline.getConfig(), TemplateConfiguration.class);
// `templatedPipeline.getConfig()` above was …
```

fix(web): Retrieve dependent pipelines correctly

---

front50-core/src/main/java/com/netflix/spinnaker/front50/model/ObjectType.java
front50-gcs/src/main/java/com/netflix/spinnaker/front50/config/GcsConfig.java
front50-gcs/src/main/kotlin/com/netflix/spinnaker/front50/model/GcsStorageService.kt
front50-gcs/src/test/kotlin/com/netflix/spinnaker/front50/model/TestGcsStorageService.kt

Previous implementation was not correctly distinguishing between APPLICATION and APPLICATION_PERMISSION metadata leading to a migrator deserialisation issue for GCS to SQL Front50 migration.
This PR fixes this with a small refactor. 
Fixes https://github.com/spinnaker/spinnaker/issues/6957

fix(migrator): GCS to SQL migrator APPLICATION_PERMISSION objectType fix

---

front50-api/src/main/java/com/netflix/spinnaker/front50/api/model/pipeline/Pipeline.java
front50-sql/src/main/kotlin/com/netflix/spinnaker/front50/model/SqlStorageService.kt
front50-sql/src/test/kotlin/com/netflix/spinnaker/front50/model/SqlStorageServiceTests.kt
front50-web/src/main/java/com/netflix/spinnaker/front50/config/Front50WebConfig.java
front50-web/src/main/java/com/netflix/spinnaker/front50/config/controllers/PipelineControllerConfig.java
front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/PipelineController.java
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/PipelineControllerSpec.groovy
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/PipelineControllerTck.groovy

This PR adds the following functionality to pipeline batch update operation :
- refactor bulk storage operation to make it atomic
- add duplicate pipeline check to /pipelines POST handler method (i.e. save individual pipeline) and  /pipelines/{id} PUT handler method (i.e. update individual pipeline)
- update /pipelines/batchUpdate POST handler method to address deserialization issues and add some useful log statements
- adds configurable controls to decide whether cache should be refreshed while checking for duplicate pipelines 
```yaml
controller:
pipeline:
save:
refreshCacheOnDuplicatesCheck: false // default is true 
```
- Add pipeline validations to validate all the deserialized pipelines
-  batchUpdate now responds with a status of succeeded and failed pipelines info. The response …

feat(batchUpdate): enhance batch update functionality

---

.github/workflows/release.yml

Since halyard uses a different versioning scheme, it doesn't make sense for halyard to consume non-master (e.g. release-1.34.x) versions of front50.
Similar to https://github.com/spinnaker/clouddriver/pull/6268 + https://github.com/spinnaker/clouddriver/pull/6271.

fix(gha): only bump halyard on master

---

front50-core/src/main/java/com/netflix/spinnaker/front50/model/ObjectType.java
front50-gcs/src/test/kotlin/com/netflix/spinnaker/front50/model/TestGcsStorageService.kt

By fixing the GCS to SQL migration in this [PR](https://github.com/spinnaker/front50/pull/1466) and removing the hardcoded "specification.json" from the GCSStorageService i cause an issue with all ObjectTypes except the Application and ApplicationPermission.
More specifically the offending change is this [one](https://github.com/spinnaker/front50/pull/1466/files#diff-ad1315a92ee2c9fdab8045580939d3fc728072a1cf2bcb709f99ba2be841f4d3R286) which had an effect in all the other ObjectTypes in GCS to get/store the filenames defined in the ObjectType and not the previously used `specification.json` for GCS.
Fixes issue https://github.com/spinnaker/spinnaker/issues/6970

fix(front50-gcs): Fix ObjectType filenames for GCS Front50 persistent store

---

build.gradle
front50-web/front50-web.gradle
front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/AdminController.java
front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/DeliveryController.java
front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/PermissionsController.java
front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/v2/ApplicationsController.java
front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/v2/ProjectsController.java
gradle.properties

Depends on https://github.com/spinnaker/kork/pull/1198

fix(openapi): Rewrite Swagger to OpenAPI annotations

---

front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/PipelineController.java
front50-web/src/test/groovy/com/netflix/spinnaker/front50/controllers/PipelineControllerTck.groovy

Optionally exclude the Disabled pipelines of an application. This can be opt-in by the Orca PR https://github.com/spinnaker/orca/pull/4819

feat(web): Exclude Disabled pipelines query parameter
